window.HSK3_LESSONS = window.HSK3_LESSONS || [];
window.HSK3_LESSONS.push(
/* ============ 第11课 ============ */
{id:'11-1',lessonNo:11,textNo:1,lessonTitle:'别忘了把空调关了',lessonTitleEn:"Don't forget to turn off the air conditioner",title:'在教室',titleEn:'In the Classroom',audio:'assets/11-1.mp3',sentences:[
{speaker:'小明',text:'我先走了。',py:'Wǒ xiān zǒu le.',pyChars:['wǒ','xiān','zǒu','le',''],trans:"I'm leaving first."},
{speaker:'同学',text:'你去哪儿？',py:'Nǐ qù nǎr?',pyChars:['nǐ','qù','nǎ','ér',''],trans:"Where are you going?"},
{speaker:'小明',text:'我去图书馆借本书。',py:'Wǒ qù túshūguǎn jiè běn shū.',pyChars:['wǒ','qù','tú','shū','guǎn','jiè','běn','shū',''],trans:"I'm going to the library to borrow a book."},
{speaker:'同学',text:'帮我把这本词典还了吧。',py:'Bāng wǒ bǎ zhè běn cídiǎn huán le ba.',pyChars:['bāng','wǒ','bǎ','zhè','běn','cí','diǎn','huán','le','ba',''],trans:"Help me return this dictionary."},
{speaker:'小明',text:'好，等一会儿你离开教室的时候，记得把灯关了。',py:'Hǎo, děng yíhuìr nǐ líkāi jiàoshì de shíhou, jìde bǎ dēng guān le.',pyChars:['hǎo','','děng','yí','huì','ér','nǐ','lí','kāi','jiào','shì','de','shí','hòu','','jì','de','bǎ','dēng','guān','le',''],trans:"OK. When you leave the classroom later, remember to turn off the lights."},
{speaker:'同学',text:'好的，放心吧。',py:'Hǎo de, fàngxīn ba.',pyChars:['hǎo','de','','fàng','xīn','ba',''],trans:"OK, no worries."}]},
{id:'11-2',lessonNo:11,textNo:2,lessonTitle:'别忘了把空调关了',lessonTitleEn:"Don't forget to turn off the air conditioner",title:'在会议室',titleEn:'In the Conference Room',audio:'assets/11-2.mp3',sentences:[
{speaker:'周明',text:'会议结束后，别忘记把空调关了。',py:'Huìyì jiéshù hòu, bié wàngjì bǎ kōngtiáo guān le.',pyChars:['huì','yì','jié','shù','hòu','','bié','wàng','jì','bǎ','kōng','tiáo','guān','le',''],trans:"After the meeting ends, don't forget to turn off the air conditioner."},
{speaker:'小丽',text:'好的。王经理两点左右来了个电话。',py:'Hǎo de. Wáng jīnglǐ liǎng diǎn zuǒyòu láile ge diànhuà.',pyChars:['hǎo','de','','wáng','jīng','lǐ','liǎng','diǎn','zuǒ','yòu','lái','le','ge','diàn','huà',''],trans:"OK. Manager Wang called around two o'clock."},
{speaker:'周明',text:'他已经到北京了？',py:'Tā yǐjīng dào Běijīng le?',pyChars:['tā','yǐ','jīng','dào','běi','jīng','le',''],trans:"Has he arrived in Beijing already?"},
{speaker:'小丽',text:'是的，他正坐地铁来我们公司呢。',py:'Shì de, tā zhèng zuò dìtiě lái wǒmen gōngsī ne.',pyChars:['shì','de','','tā','zhèng','zuò','dì','tiě','lái','wǒ','men','gōng','sī','ne',''],trans:"Yes. He's on the subway coming to our company now."},
{speaker:'周明',text:'等他到了就告诉我。',py:'Děng tā dào le jiù gàosu wǒ.',pyChars:['děng','tā','dào','le','jiù','gào','su','wǒ',''],trans:"Tell me when he arrives."}]},
{id:'11-3',lessonNo:11,textNo:3,lessonTitle:'别忘了把空调关了',lessonTitleEn:"Don't forget to turn off the air conditioner",title:'在客厅',titleEn:'In the Living Room',audio:'assets/11-3.mp3',sentences:[
{speaker:'妈妈',text:'还差一双筷子，你去拿一下。',py:'Hái chà yì shuāng kuàizi, nǐ qù ná yíxià.',pyChars:['hái','chà','yì','shuāng','kuài','zi','','nǐ','qù','ná','yí','xià',''],trans:"We're short one pair of chopsticks. Go get them."},
{speaker:'儿子',text:'今天怎么做了这么多菜？',py:'Jīntiān zěnme zuòle zhème duō cài?',pyChars:['jīn','tiān','zěn','me','zuò','le','zhè','me','duō','cài',''],trans:"Why did you cook so many dishes today?"},
{speaker:'妈妈',text:'今天是你爸爸的生日。',py:'Jīntiān shì nǐ bàba de shēngrì.',pyChars:['jīn','tiān','shì','nǐ','bà','ba','de','shēng','rì',''],trans:"Today is your dad's birthday."},
{speaker:'儿子',text:'真的啊？我把爸爸的生日忘了。那我们今天喝点儿啤酒吧。',py:'Zhēn de a? Wǒ bǎ bàba de shēngrì wàng le. Nà wǒmen jīntiān hē diǎnr píjiǔ ba.',pyChars:['zhēn','de','a','','wǒ','bǎ','bà','ba','de','shēng','rì','wàng','le','','nà','wǒ','men','jīn','tiān','hē','diǎn','ér','pí','jiǔ','ba',''],trans:"Really? I forgot dad's birthday. Then let's drink some beer today."},
{speaker:'妈妈',text:'医生说你爸爸一口酒都不能喝，别让他看见酒瓶子。',py:'Yīshēng shuō nǐ bàba yì kǒu jiǔ dōu bù néng hē, bié ràng tā kànjiàn jiǔ píngzi.',pyChars:['yī','shēng','shuō','nǐ','bà','ba','yì','kǒu','jiǔ','dōu','bù','néng','hē','','bié','ràng','tā','kàn','jiàn','jiǔ','píng','zi',''],trans:"The doctor said your dad can't drink even a sip of alcohol. Don't let him see the beer bottle."}]},
{id:'11-4',lessonNo:11,textNo:4,lessonTitle:'别忘了把空调关了',lessonTitleEn:"Don't forget to turn off the air conditioner",title:'短文',titleEn:'Short Passage',audio:'assets/11-4.mp3',sentences:[
{speaker:'旁白',text:'这个笔记本电脑我去年买的时候要五千块左右，',py:'Zhège bǐjìběn diànnǎo wǒ qùnián mǎi de shíhou yào wǔqiān kuài zuǒyòu,',pyChars:['zhè','ge','bǐ','jì','běn','diàn','nǎo','wǒ','qù','nián','mǎi','de','shí','hòu','yào','wǔ','qiān','kuài','zuǒ','yòu',''],trans:'This laptop cost around 5,000 yuan when I bought it last year,'},
{speaker:'旁白',text:'现在便宜多了。',py:'Xiànzài piányi duō le.',pyChars:['xiàn','zài','pián','yi','duō','le',''],trans:"It's much cheaper now."},
{speaker:'旁白',text:'我想把这个电脑卖了，再买一个更好的。',py:'Wǒ xiǎng bǎ zhège diànnǎo mài le, zài mǎi yí ge gèng hǎo de.',pyChars:['wǒ','xiǎng','bǎ','zhè','ge','diàn','nǎo','mài','le','','zài','mǎi','yí','ge','gèng','hǎo','de',''],trans:"I want to sell this computer and buy a better one."},
{speaker:'旁白',text:'现在我每天起床后的第一件事就是打开电脑，',py:'Xiànzài wǒ měi tiān qǐchuáng hòu de dì yī jiàn shì jiù shì dǎkāi diànnǎo,',pyChars:['xiàn','zài','wǒ','měi','tiān','qǐ','chuáng','hòu','de','dì','yī','jiàn','shì','jiù','shì','dǎ','kāi','diàn','nǎo',''],trans:'Now the first thing I do after getting up every day is turn on the computer,'},
{speaker:'旁白',text:'看电子邮件。',py:'Kàn diànzǐ yóujiàn.',pyChars:['kàn','diàn','zǐ','yóu','jiàn',''],trans:'and check email.'},
{speaker:'旁白',text:'我已经很少写信，也很少用笔写字，',py:'Wǒ yǐjīng hěn shǎo xiě xìn, yě hěn shǎo yòng bǐ xiě zì,',pyChars:['wǒ','yǐ','jīng','hěn','shǎo','xiě','xìn','','yě','hěn','shǎo','yòng','bǐ','xiě','zì',''],trans:"I rarely write letters now, and rarely write with a pen,"},
{speaker:'旁白',text:'已经习惯用电脑来学习和工作了。',py:'Yǐjīng xíguàn yòng diànnǎo lái xuéxí hé gōngzuò le.',pyChars:['yǐ','jīng','xí','guàn','yòng','diàn','nǎo','lái','xué','xí','hé','gōng','zuò','le',''],trans:"I'm used to studying and working with a computer."},
{speaker:'旁白',text:'哪一天突然没有了电脑，我们怎么办呢？',py:'Nǎ yì tiān tūrán méiyǒu le diànnǎo, wǒmen zěnme bàn ne?',pyChars:['nǎ','yì','tiān','tū','rán','méi','yǒu','le','diàn','nǎo','','wǒ','men','zěn','me','bàn','ne',''],trans:"If one day computers suddenly disappeared, what would we do?"}]},

/* ============ 第12课 ============ */
{id:'12-1',lessonNo:12,textNo:1,lessonTitle:'把重要的东西放在我这儿吧',lessonTitleEn:'Leave the important items with me',title:'在家',titleEn:'At Home',audio:'assets/12-1.mp3',sentences:[
{speaker:'小丽',text:'今天太阳从西边出来了吗？',py:'Jīntiān tàiyáng cóng xībiān chūlai le ma?',pyChars:['jīn','tiān','tài','yáng','cóng','xī','biān','chū','lai','le','ma',''],trans:"Did the sun rise in the west today?"},
{speaker:'小刚',text:'怎么了？',py:'Zěnme le?',pyChars:['zěn','me','le',''],trans:"What's wrong?"},
{speaker:'小丽',text:'你怎么这么早就要睡觉了？以前都要12点以后才睡觉。',py:'Nǐ zěnme zhème zǎo jiù yào shuìjiào le? Yǐqián dōu yào shí\'èr diǎn yǐhòu cái shuìjiào.',pyChars:['nǐ','zěn','me','zhè','me','zǎo','jiù','yào','shuì','jiào','le','','yǐ','qián','dōu','yào','shí','èr','diǎn','yǐ','hòu','cái','shuì','jiào',''],trans:"Why are you going to bed so early? You used to stay up past 12."},
{speaker:'小刚',text:'我明天8点就要到公司。',py:'Wǒ míngtiān bā diǎn jiù yào dào gōngsī.',pyChars:['wǒ','míng','tiān','bā','diǎn','jiù','yào','dào','gōng','sī',''],trans:"I need to be at the company at 8 tomorrow."},
{speaker:'小丽',text:'有事吗？',py:'Yǒu shì ma?',pyChars:['yǒu','shì','ma',''],trans:"Something up?"},
{speaker:'小刚',text:'经理生气了，他告诉我，明天8点不到，以后就别来了。',py:'Jīnglǐ shēngqì le, tā gàosu wǒ, míngtiān bā diǎn bú dào, yǐhòu jiù bié lái le.',pyChars:['jīng','lǐ','shēng','qì','le','','tā','gào','su','wǒ','','míng','tiān','bā','diǎn','bú','dào','','yǐ','hòu','jiù','bié','lái','le',''],trans:"The manager got angry. He told me if I'm not there at 8 tomorrow, don't come back."}]},
{id:'12-2',lessonNo:12,textNo:2,lessonTitle:'把重要的东西放在我这儿吧',lessonTitleEn:'Leave the important items with me',title:'在家',titleEn:'At Home',audio:'assets/12-2.mp3',sentences:[
{speaker:'小刚',text:'我要跟周经理去外地办事，明天的飞机。',py:'Wǒ yào gēn Zhōu jīnglǐ qù wàidì bàn shì, míngtiān de fēijī.',pyChars:['wǒ','yào','gēn','zhōu','jīng','lǐ','qù','wài','dì','bàn','shì','','míng','tiān','de','fēi','jī',''],trans:"I'm going on a business trip with Manager Zhou. Tomorrow's flight."},
{speaker:'小丽',text:'那我帮你把衣服放到行李箱里吧。什么时候回来？',py:'Nà wǒ bāng nǐ bǎ yīfu fàng dào xínglǐxiāng li ba. Shénme shíhou huílai?',pyChars:['nà','wǒ','bāng','nǐ','bǎ','yī','fu','fàng','dào','xíng','lǐ','xiāng','li','ba','','shén','me','shí','hòu','huí','lai',''],trans:"Then let me help you put the clothes in the suitcase. When will you be back?"},
{speaker:'小刚',text:'一个星期就回来。',py:'Yí ge xīngqī jiù huílai.',pyChars:['yí','ge','xīng','qī','jiù','huí','lai',''],trans:"Back in a week."},
{speaker:'小丽',text:'啊？一个星期以后才回来？',py:'A? Yí ge xīngqī yǐhòu cái huílai?',pyChars:['a','','yí','ge','xīng','qī','yǐ','hòu','cái','huí','lai',''],trans:"What? You won't be back for a whole week?"},
{speaker:'小丽',text:'你要自己照顾好自己，我已经给你准备好吃的和喝的了。',py:'Nǐ yào zìjǐ zhàogù hǎo zìjǐ, wǒ yǐjīng gěi nǐ zhǔnbèi hǎo chī de hé hē de le.',pyChars:['nǐ','yào','zì','jǐ','zhào','gù','hǎo','zì','jǐ','','wǒ','yǐ','jīng','gěi','nǐ','zhǔn','bèi','hǎo','chī','de','hé','hē','de','le',''],trans:"You need to take care of yourself. I've already prepared food and drinks for you."},
{speaker:'小丽',text:'好吧。我已经把我的照片放在你的包里了。',py:'Hǎo ba. Wǒ yǐjīng bǎ wǒ de zhàopiàn fàng zài nǐ de bāo li le.',pyChars:['hǎo','ba','','wǒ','yǐ','jīng','bǎ','wǒ','de','zhào','piàn','fàng','zài','nǐ','de','bāo','li','le',''],trans:"Alright. I've already put my photo in your bag."}]},
{id:'12-3',lessonNo:12,textNo:3,lessonTitle:'把重要的东西放在我这儿吧',lessonTitleEn:'Leave the important items with me',title:'在机场',titleEn:'At the Airport',audio:'assets/12-3.mp3',sentences:[
{speaker:'周明',text:'你怎么才来？',py:'Nǐ zěnme cái lái?',pyChars:['nǐ','zěn','me','cái','lái',''],trans:"Why are you so late?"},
{speaker:'小刚',text:'对不起，周经理，来机场的路上我才发现忘带护照了。',py:'Duìbuqǐ, Zhōu jīnglǐ, lái jīchǎng de lùshang wǒ cái fāxiàn wàng dài hùzhào le.',pyChars:['duì','bu','qǐ','','zhōu','jīng','lǐ','','lái','jī','chǎng','de','lù','shang','wǒ','cái','fā','xiàn','wàng','dài','hù','zhào','le',''],trans:"Sorry, Manager Zhou. On the way to the airport I discovered I forgot my passport."},
{speaker:'周明',text:'快点吧，飞机就要起飞了。',py:'Kuài diǎn ba, fēijī jiù yào qǐfēi le.',pyChars:['kuài','diǎn','ba','','fēi','jī','jiù','yào','qǐ','fēi','le',''],trans:"Hurry up. The plane is about to take off."},
{speaker:'小刚',text:'您有钱吗？司机把我送到机场的时候，我才发现忘记带钱包了。',py:'Nín yǒu qián ma? Sījī bǎ wǒ sòng dào jīchǎng de shíhou, wǒ cái fāxiàn wàngjì dài qiánbāo le.',pyChars:['nín','yǒu','qián','ma','','sī','jī','bǎ','wǒ','sòng','dào','jī','chǎng','de','shí','hòu','','wǒ','cái','fā','xiàn','wàng','jì','dài','qián','bāo','le',''],trans:"Do you have money? When the driver dropped me at the airport, I realized I forgot my wallet."},
{speaker:'周明',text:'我看你还是把重要的东西放在我这儿吧。',py:'Wǒ kàn nǐ háishì bǎ zhòngyào de dōngxi fàng zài wǒ zhèr ba.',pyChars:['wǒ','kàn','nǐ','hái','shì','bǎ','zhòng','yào','de','dōng','xi','fàng','zài','wǒ','zhè','ér','ba',''],trans:"I think you should just leave the important things with me."}]},
{id:'12-4',lessonNo:12,textNo:4,lessonTitle:'把重要的东西放在我这儿吧',lessonTitleEn:'Leave the important items with me',title:'短文',titleEn:'Short Passage',audio:'assets/12-4.mp3',sentences:[
{speaker:'旁白',text:'我是一个中学老师，',py:'Wǒ shì yí ge zhōngxué lǎoshī,',pyChars:['wǒ','shì','yí','ge','zhōng','xué','lǎo','shī',''],trans:"I'm a middle school teacher,"},
{speaker:'旁白',text:'教学生画画儿。',py:'Jiāo xuéshēng huà huàr.',pyChars:['jiāo','xué','shēng','huà','huà','ér',''],trans:'teaching students to draw.'},
{speaker:'旁白',text:'每次下课前，我都会把下次学生需要带的东西写在黑板上，',py:'Měi cì xià kè qián, wǒ dōu huì bǎ xià cì xuéshēng xūyào dài de dōngxi xiě zài hēibǎn shàng,',pyChars:['měi','cì','xià','kè','qián','','wǒ','dōu','huì','bǎ','xià','cì','xué','shēng','xū','yào','dài','de','dōng','xi','xiě','zài','hēi','bǎn','shàng',''],trans:'Before each class ends, I write on the blackboard what students need to bring next time,'},
{speaker:'旁白',text:'但是每次上课时，总会有学生忘了拿铅笔，',py:'Dànshì měi cì shàng kè shí, zǒng huì yǒu xuéshēng wàngle ná qiānbǐ,',pyChars:['dàn','shì','měi','cì','shàng','kè','shí','','zǒng','huì','yǒu','xué','shēng','wàng','le','ná','qiān','bǐ',''],trans:'but in every class, there are always students who forget their pencils,'},
{speaker:'旁白',text:'所以我有点儿生气，',py:'Suǒyǐ wǒ yǒudiǎnr shēngqì,',pyChars:['suǒ','yǐ','wǒ','yǒu','diǎn','ér','shēng','qì',''],trans:"so I get a bit annoyed,"},
{speaker:'旁白',text:'不是因为他们没带铅笔，是因为他们没有好的学习习惯。',py:'Bú shì yīnwèi tāmen méi dài qiānbǐ, shì yīnwèi tāmen méiyǒu hǎo de xuéxí xíguàn.',pyChars:['bú','shì','yīn','wèi','tā','men','méi','dài','qiān','bǐ','','shì','yīn','wèi','tā','men','méi','yǒu','hǎo','de','xué','xí','xí','guàn',''],trans:"not because they didn't bring pencils, but because they don't have good study habits."}]},

/* ============ 第13课 ============ */
{id:'13-1',lessonNo:13,textNo:1,lessonTitle:'我是走回来的',lessonTitleEn:'I walked back',title:'在家',titleEn:'At Home',audio:'assets/13-1.mp3',sentences:[
{speaker:'小丽',text:'你终于回来了！从哪儿买回来这么多东西啊？',py:'Nǐ zhōngyú huílai le! Cóng nǎr mǎi huílai zhème duō dōngxi a?',pyChars:['nǐ','zhōng','yú','huí','lai','le','','cóng','nǎ','ér','mǎi','huí','lai','zhè','me','duō','dōng','xi','a',''],trans:"You're finally back! Where did you buy so many things?"},
{speaker:'小刚',text:'都是从那边的商店买回来的。',py:'Dōu shì cóng nàbian de shāngdiàn mǎi huílai de.',pyChars:['dōu','shì','cóng','nà','biān','de','shāng','diàn','mǎi','huí','lai','de',''],trans:"All bought from the store over there."},
{speaker:'小丽',text:'怎么还买红酒回来了？谁喝啊？',py:'Zěnme hái mǎi hóngjiǔ huílai le? Shéi hē a?',pyChars:['zěn','me','hái','mǎi','hóng','jiǔ','huí','lai','le','','shéi','hē','a',''],trans:"Why did you buy red wine too? Who's drinking it?"},
{speaker:'小刚',text:'这是给爷爷的礼物，明天我们一起送过去，看看爷爷奶奶。',py:'Zhè shì gěi yéye de lǐwù, míngtiān wǒmen yìqǐ sòng guòqu, kànkan yéye nǎinai.',pyChars:['zhè','shì','gěi','yé','ye','de','lǐ','wù','','míng','tiān','wǒ','men','yì','qǐ','sòng','guò','qu','','kàn','kan','yé','ye','nǎi','nai',''],trans:"This is a gift for Grandpa. Let's deliver it tomorrow and visit Grandpa and Grandma."},
{speaker:'小丽',text:'那我的礼物呢？快拿出来让我看看。',py:'Nà wǒ de lǐwù ne? Kuài ná chūlai ràng wǒ kànkan.',pyChars:['nà','wǒ','de','lǐ','wù','ne','','kuài','ná','chū','lai','ràng','wǒ','kàn','kan',''],trans:"Then where's my gift? Take it out and let me see."},
{speaker:'小刚',text:'我不是已经回来了吗？',py:'Wǒ bú shì yǐjīng huílai le ma?',pyChars:['wǒ','bú','shì','yǐ','jīng','huí','lai','le','ma',''],trans:"Haven't I already come back?"}]},
{id:'13-2',lessonNo:13,textNo:2,lessonTitle:'我是走回来的',lessonTitleEn:'I walked back',title:'在家',titleEn:'At Home',audio:'assets/13-2.mp3',sentences:[
{speaker:'小丽',text:'我今天看见你和一个女的进了咖啡店，她是谁啊？',py:'Wǒ jīntiān kànjiàn nǐ hé yí ge nǚ de jìnle kāfēidiàn, tā shì shéi a?',pyChars:['wǒ','jīn','tiān','kàn','jiàn','nǐ','hé','yí','ge','nǚ','de','jìn','le','kā','fēi','diàn','','tā','shì','shéi','a',''],trans:"I saw you go into a coffee shop with a woman today. Who is she?"},
{speaker:'小刚',text:'她是我今天在路上遇到的一个老同学。',py:'Tā shì wǒ jīntiān zài lùshang yùdào de yí ge lǎo tóngxué.',pyChars:['tā','shì','wǒ','jīn','tiān','zài','lù','shang','yù','dào','de','yí','ge','lǎo','tóng','xué',''],trans:"She's an old classmate I ran into on the road today."},
{speaker:'小丽',text:'你们就一起去喝咖啡了？',py:'Nǐmen jiù yìqǐ qù hē kāfēi le?',pyChars:['nǐ','men','jiù','yì','qǐ','qù','hē','kā','fēi','le',''],trans:"So you just went to have coffee together?"},
{speaker:'小刚',text:'是啊，一边喝咖啡一边说了些过去的事。',py:'Shì a, yìbiān hē kāfēi yìbiān shuōle xiē guòqù de shì.',pyChars:['shì','a','','yì','biān','hē','kā','fēi','yì','biān','shuō','le','xiē','guò','qù','de','shì',''],trans:"Yes. We drank coffee while talking about old times."},
{speaker:'小丽',text:'你回来得这么晚，是说了很多过去的事吗？',py:'Nǐ huílai de zhème wǎn, shì shuōle hěn duō guòqù de shì ma?',pyChars:['nǐ','huí','lai','de','zhè','me','wǎn','','shì','shuō','le','hěn','duō','guò','qù','de','shì','ma',''],trans:"You came back so late. Did you talk about a lot of old times?"},
{speaker:'小刚',text:'不是。没有公共汽车了，我是走回来的。',py:'Bú shì. Méiyǒu gōnggòng qìchē le, wǒ shì zǒu huílai de.',pyChars:['bú','shì','','méi','yǒu','gōng','gòng','qì','chē','le','','wǒ','shì','zǒu','huí','lai','de',''],trans:"No. There were no more buses, so I walked back."}]},
{id:'13-3',lessonNo:13,textNo:3,lessonTitle:'我是走回来的',lessonTitleEn:'I walked back',title:'在打电话',titleEn:'On the Phone',audio:'assets/13-3.mp3',sentences:[
{speaker:'同事',text:'小丽，周末你一般跟小刚出去看电影吗？',py:'Xiǎolì, zhōumò nǐ yìbān gēn Xiǎogāng chūqu kàn diànyǐng ma?',pyChars:['xiǎo','lì','','zhōu','mò','nǐ','yì','bān','gēn','xiǎo','gāng','chū','qu','kàn','diàn','yǐng','ma',''],trans:"Xiaoli, do you usually go to the movies with Xiaogang on weekends?"},
{speaker:'小丽',text:'我很少去电影院看电影，我更愿意在家看电视。',py:'Wǒ hěn shǎo qù diànyǐngyuàn kàn diànyǐng, wǒ gèng yuànyì zài jiā kàn diànshì.',pyChars:['wǒ','hěn','shǎo','qù','diàn','yǐng','yuàn','kàn','diàn','yǐng','','wǒ','gèng','yuàn','yì','zài','jiā','kàn','diàn','shì',''],trans:"I rarely go to the cinema. I prefer watching TV at home."},
{speaker:'同事',text:'看电视有什么意思啊？',py:'Kàn diànshì yǒu shénme yìsi a?',pyChars:['kàn','diàn','shì','yǒu','shén','me','yì','si','a',''],trans:"What's the fun in watching TV?"},
{speaker:'小丽',text:'可以一边吃一边看，坐久了还可以站起来休息一会儿。',py:'Kěyǐ yìbiān chī yìbiān kàn, zuò jiǔ le hái kěyǐ zhàn qǐlai xiūxi yíhuìr.',pyChars:['kě','yǐ','yì','biān','chī','yì','biān','kàn','','zuò','jiǔ','le','hái','kě','yǐ','zhàn','qǐ','lai','xiū','xi','yí','huì','ér',''],trans:"I can eat while watching, and if I sit too long I can stand up and rest."},
{speaker:'同事',text:'你应该多出去走走，这样你们的生活会更有意思。',py:'Nǐ yīnggāi duō chūqu zǒuzou, zhèyàng nǐmen de shēnghuó huì gèng yǒu yìsi.',pyChars:['nǐ','yīng','gāi','duō','chū','qu','zǒu','zou','','zhè','yàng','nǐ','men','de','shēng','huó','huì','gèng','yǒu','yì','si',''],trans:"You should go out more. That way your life will be more interesting."},
{speaker:'小丽',text:'有他在，我的生活已经很有意思了。',py:'Yǒu tā zài, wǒ de shēnghuó yǐjīng hěn yǒu yìsi le.',pyChars:['yǒu','tā','zài','','wǒ','de','shēng','huó','yǐ','jīng','hěn','yǒu','yì','si','le',''],trans:"With him around, my life is already very interesting."}]},
{id:'13-4',lessonNo:13,textNo:4,lessonTitle:'我是走回来的',lessonTitleEn:'I walked back',title:'短文',titleEn:'Short Passage',audio:'assets/13-4.mp3',sentences:[
{speaker:'旁白',text:'刚结婚的时候，我丈夫是中学老师，',py:'Gāng jiéhūn de shíhou, wǒ zhàngfu shì zhōngxué lǎoshī,',pyChars:['gāng','jié','hūn','de','shí','hòu','','wǒ','zhàng','fu','shì','zhōng','xué','lǎo','shī',''],trans:'When we first got married, my husband was a middle school teacher,'},
{speaker:'旁白',text:'他喜欢每天早上起床后，一边吃早饭一边看报纸。',py:'Tā xǐhuan měi tiān zǎoshang qǐchuáng hòu, yìbiān chī zǎofàn yìbiān kàn bàozhǐ.',pyChars:['tā','xǐ','huan','měi','tiān','zǎo','shang','qǐ','chuáng','hòu','','yì','biān','chī','zǎo','fàn','yì','biān','kàn','bào','zhǐ',''],trans:'he liked to read the newspaper while eating breakfast every morning after getting up.'},
{speaker:'旁白',text:'十年过去了，',py:'Shí nián guòqu le,',pyChars:['shí','nián','guò','qu','le',''],trans:'Ten years have passed,'},
{speaker:'旁白',text:'现在他已经是校长了，',py:'Xiànzài tā yǐjīng shì xiàozhǎng le,',pyChars:['xiàn','zài','tā','yǐ','jīng','shì','xiào','zhǎng','le',''],trans:"now he's already a principal,"},
{speaker:'旁白',text:'因为太忙，每天早上我起床后都看不到他，',py:'Yīnwèi tài máng, měi tiān zǎoshang wǒ qǐchuáng hòu dōu kàn bu dào tā,',pyChars:['yīn','wèi','tài','máng','','měi','tiān','zǎo','shang','wǒ','qǐ','chuáng','hòu','dōu','kàn','bu','dào','tā',''],trans:"because he's too busy, I don't see him after I get up every morning,"},
{speaker:'旁白',text:'晚上很晚他才回到家。',py:'Wǎnshang hěn wǎn tā cái huídào jiā.',pyChars:['wǎn','shang','hěn','wǎn','tā','cái','huí','dào','jiā',''],trans:'and he comes home very late at night.'},
{speaker:'旁白',text:'我真怕他累坏了。',py:'Wǒ zhēn pà tā lèihuài le.',pyChars:['wǒ','zhēn','pà','tā','lèi','huài','le',''],trans:"I'm really afraid he'll work himself sick."},
{speaker:'旁白',text:'希望他能少一些会议，多一些休息，',py:'Xīwàng tā néng shǎo yìxiē huìyì, duō yìxiē xiūxi,',pyChars:['xī','wàng','tā','néng','shǎo','yì','xiē','huì','yì','','duō','yì','xiē','xiū','xi',''],trans:'I hope he can have fewer meetings and more rest,'},
{speaker:'旁白',text:'可以经常和我还有孩子在一起。',py:'Kěyǐ jīngcháng hé wǒ hái yǒu háizi zài yìqǐ.',pyChars:['kě','yǐ','jīng','cháng','hé','wǒ','hái','yǒu','hái','zi','zài','yì','qǐ',''],trans:'so he can often be with me and our child.'}]},

/* ============ 第14课 ============ */
{id:'14-1',lessonNo:14,textNo:1,lessonTitle:'你把水果拿过来',lessonTitleEn:'Please bring the fruit here',title:'在家',titleEn:'At Home',audio:'assets/14-1.mp3',sentences:[
{speaker:'周太太',text:'客人就要来了，你怎么还不打扫房间啊？',py:'Kèrén jiù yào lái le, nǐ zěnme hái bù dǎsǎo fángjiān a?',pyChars:['kè','rén','jiù','yào','lái','le','','nǐ','zěn','me','hái','bù','dǎ','sǎo','fáng','jiān','a',''],trans:"The guests are about to arrive. Why haven't you cleaned the room yet?"},
{speaker:'周明',text:'别着急，我让孩子们打扫呢，客人来的时候，他们会把房间打扫干净。',py:'Bié zháojí, wǒ ràng háizimen dǎsǎo ne, kèrén lái de shíhou, tāmen huì bǎ fángjiān dǎsǎo gānjìng.',pyChars:['bié','zháo','jí','','wǒ','ràng','hái','zi','men','dǎ','sǎo','ne','','kè','rén','lái','de','shí','hòu','','tā','men','huì','bǎ','fáng','jiān','dǎ','sǎo','gān','jìng',''],trans:"Don't worry. I've asked the kids to clean. By the time guests arrive, they'll have cleaned the room."},
{speaker:'周太太',text:'那你也不能看电视啊。',py:'Nà nǐ yě bù néng kàn diànshì a.',pyChars:['nà','nǐ','yě','bù','néng','kàn','diàn','shì','a',''],trans:"But you can't just watch TV either."},
{speaker:'周明',text:'你让我做什么？',py:'Nǐ ràng wǒ zuò shénme?',pyChars:['nǐ','ràng','wǒ','zuò','shén','me',''],trans:"What do you want me to do?"},
{speaker:'周太太',text:'先把茶和杯子放好，然后把冰箱里的西瓜拿出来。',py:'Xiān bǎ chá hé bēizi fàng hǎo, ránhòu bǎ bīngxiāng li de xīguā ná chūlai.',pyChars:['xiān','bǎ','chá','hé','bēi','zi','fàng','hǎo','','rán','hòu','bǎ','bīng','xiāng','li','de','xī','guā','ná','chū','lai',''],trans:"First set out the tea and cups, then take the watermelon out of the fridge."},
{speaker:'周明',text:'太热了，我还是先把空调打开吧。',py:'Tài rè le, wǒ háishì xiān bǎ kōngtiáo dǎkāi ba.',pyChars:['tài','rè','le','','wǒ','hái','shì','xiān','bǎ','kōng','tiáo','dǎ','kāi','ba',''],trans:"It's so hot. I'd better turn on the air conditioner first."}]},
{id:'14-2',lessonNo:14,textNo:2,lessonTitle:'你把水果拿过来',lessonTitleEn:'Please bring the fruit here',title:'在打电话',titleEn:'On the Phone',audio:'assets/14-2.mp3',sentences:[
{speaker:'同事',text:'你在忙什么呢？刚才打你的手机你也不接。',py:'Nǐ zài máng shénme ne? Gāngcái dǎ nǐ de shǒujī nǐ yě bù jiē.',pyChars:['nǐ','zài','máng','shén','me','ne','','gāng','cái','dǎ','nǐ','de','shǒu','jī','nǐ','yě','bù','jiē',''],trans:"What are you busy with? You didn't answer when I called your mobile just now."},
{speaker:'小刚',text:'对不起，我刚洗了个澡，没听见。有什么事吗？',py:'Duìbuqǐ, wǒ gāng xǐle ge zǎo, méi tīngjiàn. Yǒu shénme shì ma?',pyChars:['duì','bu','qǐ','','wǒ','gāng','xǐ','le','ge','zǎo','','méi','tīng','jiàn','','yǒu','shén','me','shì','ma',''],trans:"Sorry. I just took a shower and didn't hear it. What's the matter?"},
{speaker:'同事',text:'我想问问你公司里的一些事情。',py:'Wǒ xiǎng wènwen nǐ gōngsī li de yìxiē shìqing.',pyChars:['wǒ','xiǎng','wèn','wen','nǐ','gōng','sī','li','de','yì','xiē','shì','qing',''],trans:"I want to ask you about some things at the company."},
{speaker:'小刚',text:'你先等一下，我去把电视关了。',py:'Nǐ xiān děng yíxià, wǒ qù bǎ diànshì guān le.',pyChars:['nǐ','xiān','děng','yí','xià','','wǒ','qù','bǎ','diàn','shì','guān','le',''],trans:"Wait a moment. Let me go turn off the TV."},
{speaker:'同事',text:'没关系，你先把电视节目看完吧，然后再给我回电话。',py:'Méi guānxi, nǐ xiān bǎ diànshì jiémù kànwán ba, ránhòu zài gěi wǒ huí diànhuà.',pyChars:['méi','guān','xi','','nǐ','xiān','bǎ','diàn','shì','jié','mù','kàn','wán','ba','','rán','hòu','zài','gěi','wǒ','huí','diàn','huà',''],trans:"It's fine. Finish the TV program first, then call me back."}]},
{id:'14-3',lessonNo:14,textNo:3,lessonTitle:'你把水果拿过来',lessonTitleEn:'Please bring the fruit here',title:'在小明家',titleEn:"At Xiaoming's Home",audio:'assets/14-3.mp3',sentences:[
{speaker:'同学',text:'今晚的月亮真漂亮，像白色的盘子一样。',py:'Jīn wǎn de yuèliang zhēn piàoliang, xiàng báisè de pánzi yíyàng.',pyChars:['jīn','wǎn','de','yuè','liang','zhēn','piào','liang','','xiàng','bái','sè','de','pán','zi','yí','yàng',''],trans:"The moon tonight is so beautiful, like a white plate."},
{speaker:'小明',text:'是啊，外边也不刮风，我们坐在外边一边看月亮一边吃东西，怎么样？',py:'Shì a, wàibiān yě bù guā fēng, wǒmen zuò zài wàibiān yìbiān kàn yuèliang yìbiān chī dōngxi, zěnmeyàng?',pyChars:['shì','a','','wài','biān','yě','bù','guā','fēng','','wǒ','men','zuò','zài','wài','biān','yì','biān','kàn','yuè','liang','yì','biān','chī','dōng','xi','','zěn','me','yàng',''],trans:"Yes. And there's no wind outside. How about we sit outside, watching the moon while eating?"},
{speaker:'同学',text:'好啊，我先把桌椅搬出去，然后你把水果拿过来，我们听叔叔阿姨讲讲他们年轻时候的故事。',py:'Hǎo a, wǒ xiān bǎ zhuōyǐ bān chūqu, ránhòu nǐ bǎ shuǐguǒ ná guòlai, wǒmen tīng shūshu āyí jiǎngjiang tāmen niánqīng shíhou de gùshi.',pyChars:['hǎo','a','','wǒ','xiān','bǎ','zhuō','yǐ','bān','chū','qu','','rán','hòu','nǐ','bǎ','shuǐ','guǒ','ná','guò','lai','','wǒ','men','tīng','shū','shu','ā','yí','jiǎng','jiang','tā','men','nián','qīng','shí','hòu','de','gù','shi',''],trans:"OK. I'll move the table and chairs out first, then you bring the fruit over. We'll listen to Uncle and Auntie tell stories from their youth."},
{speaker:'小明',text:'太好了！记得给大山打个电话，让他马上过来。',py:'Tài hǎo le! Jìde gěi Dàshān dǎ ge diànhuà, ràng tā mǎshàng guòlai.',pyChars:['tài','hǎo','le','','jì','de','gěi','dà','shān','dǎ','ge','diàn','huà','','ràng','tā','mǎ','shàng','guò','lai',''],trans:"Great! Remember to call Dashan and tell him to come right away."},
{speaker:'同学',text:'不用打了，你听外边的声音，一定是大山。',py:'Bú yòng dǎ le, nǐ tīng wàibiān de shēngyīn, yídìng shì Dàshān.',pyChars:['bú','yòng','dǎ','le','','nǐ','tīng','wài','biān','de','shēng','yīn','','yí','dìng','shì','dà','shān',''],trans:"No need. Listen to the sound outside — it must be Dashan."}]},
{id:'14-4',lessonNo:14,textNo:4,lessonTitle:'你把水果拿过来',lessonTitleEn:'Please bring the fruit here',title:'短文',titleEn:'Short Passage',audio:'assets/14-4.mp3',sentences:[
{speaker:'旁白',text:'你吃过水果饭吗？',py:'Nǐ chīguo shuǐguǒ fàn ma?',pyChars:['nǐ','chī','guo','shuǐ','guǒ','fàn','ma',''],trans:'Have you ever eaten fruit rice?'},
{speaker:'旁白',text:'你在饭馆的菜单上见过水果饭吗？',py:'Nǐ zài fànguǎn de càidān shàng jiànguo shuǐguǒ fàn ma?',pyChars:['nǐ','zài','fàn','guǎn','de','cài','dān','shàng','jiàn','guo','shuǐ','guǒ','fàn','ma',''],trans:'Have you seen fruit rice on a restaurant menu?'},
{speaker:'旁白',text:'你想学着做水果饭吗？',py:'Nǐ xiǎng xuézhe zuò shuǐguǒ fàn ma?',pyChars:['nǐ','xiǎng','xué','zhe','zuò','shuǐ','guǒ','fàn','ma',''],trans:'Do you want to learn to make fruit rice?'},
{speaker:'旁白',text:'其实做水果饭很简单，',py:'Qíshí zuò shuǐguǒ fàn hěn jiǎndān,',pyChars:['qí','shí','zuò','shuǐ','guǒ','fàn','hěn','jiǎn','dān',''],trans:"Actually it's very simple,"},
{speaker:'旁白',text:'先把米饭做好，',py:'Xiān bǎ mǐfàn zuòhǎo,',pyChars:['xiān','bǎ','mǐ','fàn','zuò','hǎo',''],trans:'first cook the rice,'},
{speaker:'旁白',text:'然后再把一块块新鲜的水果放进去，',py:'Ránhòu zài bǎ yí kuàikuài xīnxiān de shuǐguǒ fàng jìnqu,',pyChars:['rán','hòu','zài','bǎ','yí','kuài','kuài','xīn','xiān','de','shuǐ','guǒ','fàng','jìn','qu',''],trans:'then add piece after piece of fresh fruit,'},
{speaker:'旁白',text:'水果饭就做好了。',py:'Shuǐguǒ fàn jiù zuòhǎo le.',pyChars:['shuǐ','guǒ','fàn','jiù','zuò','hǎo','le',''],trans:'fruit rice is done.'},
{speaker:'旁白',text:'你可以做苹果饭、香蕉饭，',py:'Nǐ kěyǐ zuò píngguǒ fàn, xiāngjiāo fàn,',pyChars:['nǐ','kě','yǐ','zuò','píng','guǒ','fàn','','xiāng','jiāo','fàn',''],trans:'You can make apple rice, banana rice,'},
{speaker:'旁白',text:'要是你愿意，还可以做西瓜饭。',py:'Yàoshi nǐ yuànyì, hái kěyǐ zuò xīguā fàn.',pyChars:['yào','shi','nǐ','yuàn','yì','','hái','kě','yǐ','zuò','xī','guā','fàn',''],trans:'if you like, watermelon rice too.'},
{speaker:'旁白',text:'多吃新鲜水果对身体好。',py:'Duō chī xīnxiān shuǐguǒ duì shēntǐ hǎo.',pyChars:['duō','chī','xīn','xiān','shuǐ','guǒ','duì','shēn','tǐ','hǎo',''],trans:'Eating more fresh fruit is good for your health.'}]},

/* ============ 第15课 ============ */
{id:'15-1',lessonNo:15,textNo:1,lessonTitle:'其他都没什么问题',lessonTitleEn:'The rest of them are all OK',title:'在办公室',titleEn:'In the Office',audio:'assets/15-1.mp3',sentences:[
{speaker:'大山',text:'老师，我来中国留学两年了，但是我的汉语水平提高得一点儿也不快啊。',py:'Lǎoshī, wǒ lái Zhōngguó liúxué liǎng nián le, dànshì wǒ de Hànyǔ shuǐpíng tígāo de yìdiǎnr yě bú kuài a.',pyChars:['lǎo','shī','','wǒ','lái','zhōng','guó','liú','xué','liǎng','nián','le','','dàn','shì','wǒ','de','hàn','yǔ','shuǐ','píng','tí','gāo','de','yì','diǎn','ér','yě','bú','kuài','a',''],trans:"Teacher, I've studied in China for two years, but my Chinese isn't improving fast at all."},
{speaker:'老师',text:'你每天认真学习，做练习、完成作业，一直不错啊。',py:'Nǐ měi tiān rènzhēn xuéxí, zuò liànxí, wánchéng zuòyè, yìzhí búcuò a.',pyChars:['nǐ','měi','tiān','rèn','zhēn','xué','xí','','zuò','liàn','xí','','wán','chéng','zuò','yè','','yì','zhí','bú','cuò','a',''],trans:"You study hard every day, do exercises, and finish your homework. You've been doing well."},
{speaker:'大山',text:'这是我昨天的作业，您帮我看看对不对。',py:'Zhè shì wǒ zuótiān de zuòyè, nín bāng wǒ kànkan duì bu duì.',pyChars:['zhè','shì','wǒ','zuó','tiān','de','zuò','yè','','nín','bāng','wǒ','kàn','kan','duì','bu','duì',''],trans:"This is my homework from yesterday. Please help me check if it's correct."},
{speaker:'老师',text:'写得不错，除了这个句子意思有些不清楚外，其他都没什么问题。',py:'Xiě de búcuò, chúle zhège jùzi yìsi yǒuxiē bù qīngchu wài, qítā dōu méi shénme wèntí.',pyChars:['xiě','de','bú','cuò','','chú','le','zhè','ge','jù','zi','yì','si','yǒu','xiē','bù','qīng','chu','wài','','qí','tā','dōu','méi','shén','me','wèn','tí',''],trans:"Well done. Except for this sentence whose meaning is a bit unclear, everything else is fine."},
{speaker:'大山',text:'谢谢老师！',py:'Xièxie lǎoshī!',pyChars:['xiè','xie','lǎo','shī',''],trans:'Thank you, teacher!'},
{speaker:'老师',text:'以后有什么不明白的地方，可以给我打电话或者发电子邮件。',py:'Yǐhòu yǒu shénme bù míngbai de dìfang, kěyǐ gěi wǒ dǎ diànhuà huòzhě fā diànzǐ yóujiàn.',pyChars:['yǐ','hòu','yǒu','shén','me','bù','míng','bai','de','dì','fang','','kě','yǐ','gěi','wǒ','dǎ','diàn','huà','huò','zhě','fā','diàn','zǐ','yóu','jiàn',''],trans:"If you don't understand something in the future, you can call me or send an email."}]},
{id:'15-2',lessonNo:15,textNo:2,lessonTitle:'其他都没什么问题',lessonTitleEn:'The rest of them are all OK',title:'在教室',titleEn:'In the Classroom',audio:'assets/15-2.mp3',sentences:[
{speaker:'学生',text:'老师，除了小云，其他人都来了。',py:'Lǎoshī, chúle Xiǎoyún, qítā rén dōu lái le.',pyChars:['lǎo','shī','','chú','le','xiǎo','yún','','qí','tā','rén','dōu','lái','le',''],trans:'Teacher, everyone is here except Xiaoyun.'},
{speaker:'老师',text:'比赛马上就要开始了，小云怎么还没来？',py:'Bǐsài mǎshàng jiù yào kāishǐ le, Xiǎoyún zěnme hái méi lái?',pyChars:['bǐ','sài','mǎ','shàng','jiù','yào','kāi','shǐ','le','','xiǎo','yún','zěn','me','hái','méi','lái',''],trans:"The competition is about to start. Why isn't Xiaoyun here yet?"},
{speaker:'学生',text:'刚才给她打电话了，她在路上呢。',py:'Gāngcái gěi tā dǎ diànhuà le, tā zài lùshang ne.',pyChars:['gāng','cái','gěi','tā','dǎ','diàn','huà','le','','tā','zài','lù','shang','ne',''],trans:"I called her just now. She's on her way."},
{speaker:'老师',text:'不等她了，我先给大家讲讲这次比赛的要求和一些需要注意的地方。',py:'Bù děng tā le, wǒ xiān gěi dàjiā jiǎngjiang zhè cì bǐsài de yāoqiú hé yìxiē xūyào zhùyì de dìfang.',pyChars:['bù','děng','tā','le','','wǒ','xiān','gěi','dà','jiā','jiǎng','jiang','zhè','cì','bǐ','sài','de','yāo','qiú','hé','yì','xiē','xū','yào','zhù','yì','de','dì','fang',''],trans:"Let's not wait for her. I'll first tell everyone the requirements of this competition and a few things to pay attention to."},
{speaker:'学生',text:'老师，您放心，今天的比赛我们一定能拿第一。',py:'Lǎoshī, nín fàngxīn, jīntiān de bǐsài wǒmen yídìng néng ná dì yī.',pyChars:['lǎo','shī','','nín','fàng','xīn','','jīn','tiān','de','bǐ','sài','wǒ','men','yí','dìng','néng','ná','dì','yī',''],trans:"Teacher, don't worry. We'll definitely take first place in today's competition."}]},
{id:'15-3',lessonNo:15,textNo:3,lessonTitle:'其他都没什么问题',lessonTitleEn:'The rest of them are all OK',title:'在休息室',titleEn:'In the Lounge',audio:'assets/15-3.mp3',sentences:[
{speaker:'同事',text:'现在用电脑上网真方便啊！',py:'Xiànzài yòng diànnǎo shàngwǎng zhēn fāngbiàn a!',pyChars:['xiàn','zài','yòng','diàn','nǎo','shàng','wǎng','zhēn','fāng','biàn','a',''],trans:'Surfing the internet on a computer is so convenient nowadays!'},
{speaker:'小刚',text:'是啊，除了看新闻，人们还可以在网上听歌、看电影、买东西。',py:'Shì a, chúle kàn xīnwén, rénmen hái kěyǐ zài wǎngshang tīng gē, kàn diànyǐng, mǎi dōngxi.',pyChars:['shì','a','','chú','le','kàn','xīn','wén','','rén','men','hái','kě','yǐ','zài','wǎng','shang','tīng','gē','','kàn','diàn','yǐng','','mǎi','dōng','xi',''],trans:'Yes. Besides reading news, people can also listen to music, watch movies, and shop online.'},
{speaker:'同事',text:'对了，你从网上买的那件衣服呢？怎么没见你穿？',py:'Duìle, nǐ cóng wǎngshang mǎi de nà jiàn yīfu ne? Zěnme méi jiàn nǐ chuān?',pyChars:['duì','le','','nǐ','cóng','wǎng','shang','mǎi','de','nà','jiàn','yī','fu','ne','','zěn','me','méi','jiàn','nǐ','chuān',''],trans:"By the way, what about that piece of clothing you bought online? How come I haven't seen you wear it?"},
{speaker:'小刚',text:'那件衣服我穿着有点儿小，给我弟弟了。',py:'Nà jiàn yīfu wǒ chuānzhe yǒudiǎnr xiǎo, gěi wǒ dìdi le.',pyChars:['nà','jiàn','yī','fu','wǒ','chuān','zhe','yǒu','diǎn','ér','xiǎo','','gěi','wǒ','dì','di','le',''],trans:'That piece of clothing is a bit small for me, so I gave it to my younger brother.'},
{speaker:'同事',text:'他满意吗？',py:'Tā mǎnyì ma?',pyChars:['tā','mǎn','yì','ma',''],trans:'Is he satisfied?'},
{speaker:'小刚',text:'不用花钱，还有新衣服穿，他满意极了。',py:'Bú yòng huā qián, hái yǒu xīn yīfu chuān, tā mǎnyì jí le.',pyChars:['bú','yòng','huā','qián','','hái','yǒu','xīn','yī','fu','chuān','','tā','mǎn','yì','jí','le',''],trans:"No money spent, and new clothes to wear — he's extremely satisfied."}]},
{id:'15-4',lessonNo:15,textNo:4,lessonTitle:'其他都没什么问题',lessonTitleEn:'The rest of them are all OK',title:'短文',titleEn:'Short Passage',audio:'assets/15-4.mp3',sentences:[
{speaker:'旁白',text:'除了春节、中秋节以外，啤酒节也是这里很重要的一个节日。',py:'Chúle Chūnjié, Zhōngqiū Jié yǐwài, píjiǔjié yě shì zhèlǐ hěn zhòngyào de yí ge jiérì.',pyChars:['chú','le','chūn','jié','','zhōng','qiū','jié','yǐ','wài','','pí','jiǔ','jié','yě','shì','zhè','lǐ','hěn','zhòng','yào','de','yí','ge','jié','rì',''],trans:'Besides Spring Festival and Mid-Autumn Festival, the Beer Festival is also an important holiday here.'},
{speaker:'旁白',text:'这个地方每年夏天都要举行一次啤酒节。',py:'Zhège dìfang měi nián xiàtiān dōu yào jǔxíng yí cì píjiǔjié.',pyChars:['zhè','ge','dì','fang','měi','nián','xià','tiān','dōu','yào','jǔ','xíng','yí','cì','pí','jiǔ','jié',''],trans:'This place holds a Beer Festival once every summer.'},
{speaker:'旁白',text:'在啤酒节上，你可以喝到世界上不同地方的啤酒。',py:'Zài píjiǔjié shàng, nǐ kěyǐ hē dào shìjiè shàng bùtóng dìfang de píjiǔ.',pyChars:['zài','pí','jiǔ','jié','shàng','','nǐ','kě','yǐ','hē','dào','shì','jiè','shàng','bù','tóng','dì','fang','de','pí','jiǔ',''],trans:'At the Beer Festival, you can drink beer from different parts of the world.'},
{speaker:'旁白',text:'除了喝啤酒，你还可以在街道两边看到世界上不同地方的歌舞。',py:'Chúle hē píjiǔ, nǐ hái kěyǐ zài jiēdào liǎngbiān kàndào shìjiè shàng bùtóng dìfang de gēwǔ.',pyChars:['chú','le','hē','pí','jiǔ','','nǐ','hái','kě','yǐ','zài','jiē','dào','liǎng','biān','kàn','dào','shì','jiè','shàng','bù','tóng','dì','fang','de','gē','wǔ',''],trans:'Besides drinking beer, you can also watch songs and dances from different parts of the world on both sides of the street.'},
{speaker:'旁白',text:'你想不想了解世界各个地方的啤酒文化？',py:'Nǐ xiǎng bu xiǎng liǎojiě shìjiè gège dìfang de píjiǔ wénhuà?',pyChars:['nǐ','xiǎng','bu','xiǎng','liǎo','jiě','shì','jiè','gè','ge','dì','fang','de','pí','jiǔ','wén','huà',''],trans:'Would you like to learn about beer cultures from all over the world?'},
{speaker:'旁白',text:'来这里的啤酒节看看吧。',py:'Lái zhèlǐ de píjiǔjié kànkan ba.',pyChars:['lái','zhè','lǐ','de','pí','jiǔ','jié','kàn','kan','ba',''],trans:'Come and check out the Beer Festival here.'}]}
);