window.HSK3_LESSONS = window.HSK3_LESSONS || [];
window.HSK3_LESSONS.push(
/* ============ 第16课 ============ */
{id:'16-1',lessonNo:16,textNo:1,lessonTitle:'我现在累得下了班就想睡觉',lessonTitleEn:'I am so tired that I want to do nothing but sleep after work',title:'在公司',titleEn:'In the Company',audio:'assets/16-1.mp3',sentences:[
{speaker:'小丽',text:'我不喜欢一直住在同一个城市，想去其他城市看一看。',py:'Wǒ bù xǐhuan yìzhí zhù zài tóng yí ge chéngshì, xiǎng qù qítā chéngshì kàn yi kàn.',pyChars:['wǒ','bù','xǐ','huan','yì','zhí','zhù','zài','tóng','yí','ge','chéng','shì','','xiǎng','qù','qí','tā','chéng','shì','kàn','yi','kàn',''],trans:"I don't like living in the same city all the time. I want to see other cities."},
{speaker:'周明',text:'我年轻的时候也这么想，但是那时候没有钱，如果有钱，就去了。',py:'Wǒ niánqīng de shíhou yě zhème xiǎng, dànshì nà shíhou méiyǒu qián, rúguǒ yǒu qián, jiù qù le.',pyChars:['wǒ','nián','qīng','de','shí','hòu','yě','zhè','me','xiǎng','','dàn','shì','nà','shí','hòu','méi','yǒu','qián','','rú','guǒ','yǒu','qián','','jiù','qù','le',''],trans:"I thought the same when I was young, but I had no money then. If I'd had money, I would have gone."},
{speaker:'小丽',text:'那您现在为什么不去？',py:'Nà nín xiànzài wèi shénme bú qù?',pyChars:['nà','nín','xiàn','zài','wèi','shén','me','bú','qù',''],trans:"Then why don't you go now?"},
{speaker:'周明',text:'现在钱不是问题了，主要是没有时间。',py:'Xiànzài qián bú shì wèntí le, zhǔyào shì méiyǒu shíjiān.',pyChars:['xiàn','zài','qián','bú','shì','wèn','tí','le','','zhǔ','yào','shì','méi','yǒu','shí','jiān',''],trans:'Money is no longer the problem now. The main thing is I have no time.'},
{speaker:'小丽',text:'我认为现在您有时间也不会出去玩儿。',py:'Wǒ rènwéi xiànzài nín yǒu shíjiān yě bú huì chūqu wánr.',pyChars:['wǒ','rèn','wéi','xiàn','zài','nín','yǒu','shí','jiān','yě','bú','huì','chū','qu','wán','ér',''],trans:"I think even if you had time now, you wouldn't go out to have fun."},
{speaker:'周明',text:'你说得对，我现在累得下了班就想睡觉。',py:'Nǐ shuō de duì, wǒ xiànzài lèi de xiàle bān jiù xiǎng shuìjiào.',pyChars:['nǐ','shuō','de','duì','','wǒ','xiàn','zài','lèi','de','xià','le','bān','jiù','xiǎng','shuì','jiào',''],trans:"You're right. I'm so tired now that I just want to sleep after work."}]},
{id:'16-2',lessonNo:16,textNo:2,lessonTitle:'我现在累得下了班就想睡觉',lessonTitleEn:'I am so tired that I want to do nothing but sleep after work',title:'在同事家',titleEn:"At a Colleague's Home",audio:'assets/16-2.mp3',sentences:[
{speaker:'同事',text:'谢谢你们来看我女儿。你送的小皮鞋和小帽子真漂亮！',py:'Xièxie nǐmen lái kàn wǒ nǚ\'ér. Nǐ sòng de xiǎo píxié hé xiǎo màozi zhēn piàoliang!',pyChars:['xiè','xie','nǐ','men','lái','kàn','wǒ','nǚ','ér','','nǐ','sòng','de','xiǎo','pí','xié','hé','xiǎo','mào','zi','zhēn','piào','liang',''],trans:"Thanks for coming to see my daughter. The little leather shoes and hat you gave are so pretty!"},
{speaker:'小丽',text:'别客气，你女儿长得白白的、胖胖的，真可爱！现在多高了？',py:'Bié kèqi, nǐ nǚ\'ér zhǎng de báibái de, pàngpàng de, zhēn kě\'ài! Xiànzài duō gāo le?',pyChars:['bié','kè','qi','','nǐ','nǚ','ér','zhǎng','de','bái','bái','de','','pàng','pàng','de','','zhēn','kě','ài','','xiàn','zài','duō','gāo','le',''],trans:"Don't mention it. Your daughter is so fair and chubby — really cute! How tall is she now?"},
{speaker:'同事',text:'快1米了，25公斤。',py:'Kuài yì mǐ le, èrshíwǔ gōngjīn.',pyChars:['kuài','yì','mǐ','le','','èr','shí','wǔ','gōng','jīn',''],trans:'Almost 1 meter, 25 kilos.'},
{speaker:'小丽',text:'你看她鼻子小小的，头发黑黑的；长得像谁？',py:'Nǐ kàn tā bízi xiǎoxiǎo de, tóufa hēihēi de; zhǎng de xiàng shéi?',pyChars:['nǐ','kàn','tā','bí','zi','xiǎo','xiǎo','de','','tóu','fa','hēi','hēi','de','','zhǎng','de','xiàng','shéi',''],trans:'Look, she has a tiny nose and black hair; who does she look like?'},
{speaker:'同事',text:'像她爸爸，刚出生时她爸爸高兴得一个晚上都没睡着。',py:'Xiàng tā bàba, gāng chūshēng shí tā bàba gāoxìng de yí ge wǎnshang dōu méi shuìzháo.',pyChars:['xiàng','tā','bà','ba','','gāng','chū','shēng','shí','tā','bà','ba','gāo','xìng','de','yí','ge','wǎn','shang','dōu','méi','shuì','zháo',''],trans:"Like her dad. When she was born, her dad was so happy he couldn't sleep all night."}]},
{id:'16-3',lessonNo:16,textNo:3,lessonTitle:'我现在累得下了班就想睡觉',lessonTitleEn:'I am so tired that I want to do nothing but sleep after work',title:'在公司',titleEn:'In the Company',audio:'assets/16-3.mp3',sentences:[
{speaker:'小刚',text:'我的牙还是很疼。',py:'Wǒ de yá háishì hěn téng.',pyChars:['wǒ','de','yá','hái','shì','hěn','téng',''],trans:'My tooth still hurts a lot.'},
{speaker:'同事',text:'如果不舒服，就去医院检查一下吧。',py:'Rúguǒ bù shūfu, jiù qù yīyuàn jiǎnchá yíxià ba.',pyChars:['rú','guǒ','bù','shū','fu','','jiù','qù','yī','yuàn','jiǎn','chá','yí','xià','ba',''],trans:"If you don't feel well, go to the hospital for a check-up."},
{speaker:'小刚',text:'检查好几次了，但是没什么用。',py:'Jiǎnchá hǎo jǐ cì le, dànshì méi shénme yòng.',pyChars:['jiǎn','chá','hǎo','jǐ','cì','le','','dàn','shì','méi','shén','me','yòng',''],trans:"I've been checked several times, but it doesn't help."},
{speaker:'同事',text:'大夫怎么说的？',py:'Dàifu zěnme shuō de?',pyChars:['dài','fu','zěn','me','shuō','de',''],trans:'What did the doctor say?'},
{speaker:'小刚',text:'每次医生都告诉我，回家好好儿刷牙。',py:'Měi cì yīshēng dōu gàosu wǒ, huí jiā hǎohāor shuā yá.',pyChars:['měi','cì','yī','shēng','dōu','gào','su','wǒ','','huí','jiā','hǎo','hāo','ér','shuā','yá',''],trans:'Every time the doctor tells me to brush my teeth well at home.'}]},
{id:'16-4',lessonNo:16,textNo:4,lessonTitle:'我现在累得下了班就想睡觉',lessonTitleEn:'I am so tired that I want to do nothing but sleep after work',title:'短文',titleEn:'Short Passage',audio:'assets/16-4.mp3',sentences:[
{speaker:'旁白',text:'很多人都觉得现在人和人的关系冷冷的，',py:'Hěn duō rén dōu juéde xiànzài rén hé rén de guānxi lěnglěng de,',pyChars:['hěn','duō','rén','dōu','jué','de','xiàn','zài','rén','hé','rén','de','guān','xi','lěng','lěng','de',''],trans:'Many people feel that relationships between people nowadays are cold,'},
{speaker:'旁白',text:'这可能是因为工作太忙，',py:'Zhè kěnéng shì yīnwèi gōngzuò tài máng,',pyChars:['zhè','kě','néng','shì','yīn','wèi','gōng','zuò','tài','máng',''],trans:'this may be because work is too busy,'},
{speaker:'旁白',text:'忙得没时间跟别人见面，',py:'Máng de méi shíjiān gēn biérén jiànmiàn,',pyChars:['máng','de','méi','shí','jiān','gēn','bié','rén','jiàn','miàn',''],trans:'so busy that there is no time to meet others,'},
{speaker:'旁白',text:'累得不愿意和别人多说话。',py:'Lèi de bú yuànyì hé biérén duō shuō huà.',pyChars:['lèi','de','bú','yuàn','yì','hé','bié','rén','duō','shuō','huà',''],trans:'so tired that one is unwilling to talk much with others.'},
{speaker:'旁白',text:'其实，我们应该多对别人笑笑，',py:'Qíshí, wǒmen yīnggāi duō duì biérén xiàoxiao,',pyChars:['qí','shí','','wǒ','men','yīng','gāi','duō','duì','bié','rén','xiào','xiao',''],trans:'Actually, we should smile more at others,'},
{speaker:'旁白',text:'说话时如果能多用一些“您好”“谢谢”这样的词语，',py:'Shuō huà shí rúguǒ néng duō yòng yìxiē “nín hǎo”“xièxie” zhèyàng de cíyǔ,',pyChars:['shuō','huà','shí','rú','guǒ','néng','duō','yòng','yì','xiē','','nín','hǎo','','','xiè','xie','','zhè','yàng','de','cí','yǔ',''],trans:'if we can use more words like “hello” and “thank you” when speaking,'},
{speaker:'旁白',text:'和别人的关系就会变得更好。',py:'Hé biérén de guānxi jiù huì biàn de gèng hǎo.',pyChars:['hé','bié','rén','de','guān','xi','jiù','huì','biàn','de','gèng','hǎo',''],trans:'our relationships with others will become better.'}]},

/* ============ 第17课 ============ */
{id:'17-1',lessonNo:17,textNo:1,lessonTitle:'谁都有办法看好你的“病”',lessonTitleEn:'Everybody is able to cure your "disease"',title:'在公司',titleEn:'In the Company',audio:'assets/17-1.mp3',sentences:[
{speaker:'小丽',text:'周经理，下个星期我可以请几天假吗？',py:'Zhōu jīnglǐ, xià ge xīngqī wǒ kěyǐ qǐng jǐ tiān jià ma?',pyChars:['zhōu','jīng','lǐ','','xià','ge','xīng','qī','wǒ','kě','yǐ','qǐng','jǐ','tiān','jià','ma',''],trans:'Manager Zhou, can I take a few days off next week?'},
{speaker:'周明',text:'你有什么事？',py:'Nǐ yǒu shénme shì?',pyChars:['nǐ','yǒu','shén','me','shì',''],trans:'What do you need it for?'},
{speaker:'小丽',text:'我的一个老朋友结婚，我跟他两年没见了。',py:'Wǒ de yí ge lǎo péngyou jiéhūn, wǒ gēn tā liǎng nián méi jiàn le.',pyChars:['wǒ','de','yí','ge','lǎo','péng','you','jié','hūn','','wǒ','gēn','tā','liǎng','nián','méi','jiàn','le',''],trans:"An old friend of mine is getting married. I haven't seen him in two years."},
{speaker:'周明',text:'你一共想请几天假？',py:'Nǐ yígòng xiǎng qǐng jǐ tiān jià?',pyChars:['nǐ','yí','gòng','xiǎng','qǐng','jǐ','tiān','jià',''],trans:'How many days off in total?'},
{speaker:'小丽',text:'三天。',py:'Sān tiān.',pyChars:['sān','tiān',''],trans:'Three days.'}]},
{id:'17-2',lessonNo:17,textNo:2,lessonTitle:'谁都有办法看好你的“病”',lessonTitleEn:'Everybody is able to cure your "disease"',title:'在公司',titleEn:'In the Company',audio:'assets/17-2.mp3',sentences:[
{speaker:'同事',text:'小丽，那个高高的男人是你们公司的吗？你对他了解吗？',py:'Xiǎolì, nàge gāogāo de nánrén shì nǐmen gōngsī de ma? Nǐ duì tā liǎojiě ma?',pyChars:['xiǎo','lì','','nà','ge','gāo','gāo','de','nán','rén','shì','nǐ','men','gōng','sī','de','ma','','nǐ','duì','tā','liǎo','jiě','ma',''],trans:'Xiaoli, is that tall man from your company? Do you know him well?'},
{speaker:'小丽',text:'我们过去是邻居，后来是大学同学，关系一直很不错。',py:'Wǒmen guòqù shì línjū, hòulái shì dàxué tóngxué, guānxi yìzhí hěn búcuò.',pyChars:['wǒ','men','guò','qù','shì','lín','jū','','hòu','lái','shì','dà','xué','tóng','xué','','guān','xi','yì','zhí','hěn','bú','cuò',''],trans:'We used to be neighbors, then college classmates. We have always gotten along well.'},
{speaker:'同事',text:'他一般喜欢做什么？',py:'Tā yìbān xǐhuan zuò shénme?',pyChars:['tā','yì','bān','xǐ','huan','zuò','shén','me',''],trans:'What does he usually like to do?'},
{speaker:'小丽',text:'他有很多爱好，唱歌、画画儿、踢足球，什么都会。',py:'Tā yǒu hěn duō àihào, chàng gē, huà huàr, tī zúqiú, shénme dōu huì.',pyChars:['tā','yǒu','hěn','duō','ài','hào','','chàng','gē','','huà','huà','ér','','tī','zú','qiú','','shén','me','dōu','huì',''],trans:'He has many hobbies — singing, painting, playing football. He can do everything.'},
{speaker:'同事',text:'真的？那你介绍我们认识认识吧。',py:'Zhēn de? Nà nǐ jièshào wǒmen rènshi rènshi ba.',pyChars:['zhēn','de','','nà','nǐ','jiè','shào','wǒ','men','rèn','shi','rèn','shi','ba',''],trans:"Really? Then introduce us!"},
{speaker:'小丽',text:'不行，现在他是我丈夫。',py:'Bù xíng, xiànzài tā shì wǒ zhàngfu.',pyChars:['bù','xíng','','xiàn','zài','tā','shì','wǒ','zhàng','fu',''],trans:"No. He's my husband now."}]},
{id:'17-3',lessonNo:17,textNo:3,lessonTitle:'谁都有办法看好你的“病”',lessonTitleEn:'Everybody is able to cure your "disease"',title:'在家',titleEn:'At Home',audio:'assets/17-3.mp3',sentences:[
{speaker:'周太太',text:'最近我觉得哪儿都不舒服，你带我去医院检查检查吧。',py:'Zuìjìn wǒ juéde nǎr dōu bù shūfu, nǐ dài wǒ qù yīyuàn jiǎnchá jiǎnchá ba.',pyChars:['zuì','jìn','wǒ','jué','de','nǎ','ér','dōu','bù','shū','fu','','nǐ','dài','wǒ','qù','yī','yuàn','jiǎn','chá','jiǎn','chá','ba',''],trans:"Lately I feel uncomfortable all over. Take me to the hospital for a check-up."},
{speaker:'周明',text:'不用去医院，谁都有办法看好你的“病”。我问你，你多久没运动了？',py:'Bú yòng qù yīyuàn, shéi dōu yǒu bànfǎ kànhǎo nǐ de “bìng”. Wǒ wèn nǐ, nǐ duō jiǔ méi yùndòng le?',pyChars:['bú','yòng','qù','yī','yuàn','','shéi','dōu','yǒu','bàn','fǎ','kàn','hǎo','nǐ','de','','bìng','','','wǒ','wèn','nǐ','','nǐ','duō','jiǔ','méi','yùn','dòng','le',''],trans:'No need for the hospital. Everyone knows how to cure your "disease". Let me ask: how long since you exercised?'},
{speaker:'周太太',text:'我三年没运动了。',py:'Wǒ sān nián méi yùndòng le.',pyChars:['wǒ','sān','nián','méi','yùn','dòng','le',''],trans:"I haven't exercised in three years."},
{speaker:'周明',text:'谁都知道运动对身体好。但是你吃饱了就睡。',py:'Shéi dōu zhīdào yùndòng duì shēntǐ hǎo. Dànshì nǐ chībǎo le jiù shuì.',pyChars:['shéi','dōu','zhī','dào','yùn','dòng','duì','shēn','tǐ','hǎo','','dàn','shì','nǐ','chī','bǎo','le','jiù','shuì',''],trans:'Everyone knows exercise is good for health. But you go to sleep right after eating.'},
{speaker:'周太太',text:'为了健康，我真应该多锻炼锻炼了。从明天起，我决定每天去长跑。',py:'Wèile jiànkāng, wǒ zhēn yīnggāi duō duànliàn duànliàn le. Cóng míngtiān qǐ, wǒ juédìng měi tiān qù chángpǎo.',pyChars:['wèi','le','jiàn','kāng','','wǒ','zhēn','yīng','gāi','duō','duàn','liàn','duàn','liàn','le','','cóng','míng','tiān','qǐ','','wǒ','jué','dìng','měi','tiān','qù','cháng','pǎo',''],trans:"For my health, I really should exercise more. Starting tomorrow, I've decided to go running every day."}]},
{id:'17-4',lessonNo:17,textNo:4,lessonTitle:'谁都有办法看好你的“病”',lessonTitleEn:'Everybody is able to cure your "disease"',title:'短文',titleEn:'Short Passage',audio:'assets/17-4.mp3',sentences:[
{speaker:'旁白',text:'“运动很重要”这句话谁都懂。',py:'“Yùndòng hěn zhòngyào” zhè jù huà shéi dōu dǒng.',pyChars:['','yùn','dòng','hěn','zhòng','yào','','zhè','jù','huà','shéi','dōu','dǒng',''],trans:'Everyone understands the saying "exercise is very important".'},
{speaker:'旁白',text:'但是你知道怎么运动吗？',py:'Dànshì nǐ zhīdào zěnme yùndòng ma?',pyChars:['dàn','shì','nǐ','zhī','dào','zěn','me','yùn','dòng','ma',''],trans:'But do you know how to exercise?'},
{speaker:'旁白',text:'第一，要选择“对”的时间。',py:'Dì yī, yào xuǎnzé “duì” de shíjiān.',pyChars:['dì','yī','','yào','xuǎn','zé','','duì','','de','shí','jiān',''],trans:'First, choose the "right" time.'},
{speaker:'旁白',text:'一般来说，早上9点是最好的时间，冬天要再晚一些。',py:'Yìbān lái shuō, zǎoshang jiǔ diǎn shì zuì hǎo de shíjiān, dōngtiān yào zài wǎn yìxiē.',pyChars:['yì','bān','lái','shuō','','zǎo','shang','jiǔ','diǎn','shì','zuì','hǎo','de','shí','jiān','','dōng','tiān','yào','zài','wǎn','yì','xiē',''],trans:'Generally speaking, 9 a.m. is the best time; in winter it should be a bit later.'},
{speaker:'旁白',text:'第二，要选择“对”的地点，',py:'Dì èr, yào xuǎnzé “duì” de dìdiǎn,',pyChars:['dì','èr','','yào','xuǎn','zé','','duì','','de','dì','diǎn',''],trans:'Second, choose the "right" place,'},
{speaker:'旁白',text:'公园、山上、游泳馆，这些地方都可以运动。',py:'Gōngyuán, shānshang, yóuyǒngguǎn, zhèxiē dìfang dōu kěyǐ yùndòng.',pyChars:['gōng','yuán','','shān','shang','','yóu','yǒng','guǎn','','zhè','xiē','dì','fang','dōu','kě','yǐ','yùn','dòng',''],trans:'Parks, mountains, swimming pools — all these places work.'},
{speaker:'旁白',text:'第三，必须要根据自己的健康情况运动。',py:'Dì sān, bìxū yào gēnjù zìjǐ de jiànkāng qíngkuàng yùndòng.',pyChars:['dì','sān','','bì','xū','yào','gēn','jù','zì','jǐ','de','jiàn','kāng','qíng','kuàng','yùn','dòng',''],trans:'Third, you must exercise according to your own health condition.'},
{speaker:'旁白',text:'如果你很久没爬山或者游泳了，',py:'Rúguǒ nǐ hěn jiǔ méi pá shān huòzhě yóuyǒng le,',pyChars:['rú','guǒ','nǐ','hěn','jiǔ','méi','pá','shān','huò','zhě','yóu','yǒng','le',''],trans:"If you haven't hiked or swum for a long time,"},
{speaker:'旁白',text:'运动一会儿就一定要休息休息。',py:'Yùndòng yíhuìr jiù yídìng yào xiūxi xiūxi.',pyChars:['yùn','dòng','yí','huì','ér','jiù','yí','dìng','yào','xiū','xi','xiū','xi',''],trans:'you must rest after exercising a little while.'},
{speaker:'旁白',text:'还要记得刚运动完口渴的时候，不要马上喝水。',py:'Hái yào jìde gāng yùndòng wán kǒu kě de shíhou, bú yào mǎshàng hē shuǐ.',pyChars:['hái','yào','jì','de','gāng','yùn','dòng','wán','kǒu','kě','de','shí','hòu','','bú','yào','mǎ','shàng','hē','shuǐ',''],trans:"Also remember: right after exercising when you're thirsty, don't drink water immediately."}]},

/* ============ 第18课 ============ */
{id:'18-1',lessonNo:18,textNo:1,lessonTitle:'我相信他们会同意的',lessonTitleEn:"I believe they'll agree",title:'在打电话',titleEn:'On the Phone',audio:'assets/18-1.mp3',sentences:[
{speaker:'朋友',text:'老周，我打算买房子了，想向你借点儿钱。',py:'Lǎo Zhōu, wǒ dǎsuàn mǎi fángzi le, xiǎng xiàng nǐ jiè diǎnr qián.',pyChars:['lǎo','zhōu','','wǒ','dǎ','suàn','mǎi','fáng','zi','le','','xiǎng','xiàng','nǐ','jiè','diǎn','ér','qián',''],trans:"Old Zhou, I'm planning to buy a house and want to borrow some money from you."},
{speaker:'周明',text:'没问题，只要我有，就一定会借给你的。还差多少？',py:'Méi wèntí, zhǐyào wǒ yǒu, jiù yídìng huì jiè gěi nǐ de. Hái chà duōshao?',pyChars:['méi','wèn','tí','','zhǐ','yào','wǒ','yǒu','','jiù','yí','dìng','huì','jiè','gěi','nǐ','de','','hái','chà','duō','shao',''],trans:"No problem. As long as I have it, I'll definitely lend it to you. How much are you short?"},
{speaker:'朋友',text:'还差5万块钱。',py:'Hái chà wǔ wàn kuài qián.',pyChars:['hái','chà','wǔ','wàn','kuài','qián',''],trans:'Still short 50,000 yuan.'},
{speaker:'周明',text:'好，钱下午打给你。你打算在哪儿买房？',py:'Hǎo, qián xiàwǔ dǎ gěi nǐ. Nǐ dǎsuàn zài nǎr mǎi fáng?',pyChars:['hǎo','','qián','xià','wǔ','dǎ','gěi','nǐ','','nǐ','dǎ','suàn','zài','nǎ','ér','mǎi','fáng',''],trans:"OK. I'll transfer the money this afternoon. Where are you planning to buy?"},
{speaker:'朋友',text:'就在我们医院前面。',py:'Jiù zài wǒmen yīyuàn qiánmiàn.',pyChars:['jiù','zài','wǒ','men','yī','yuàn','qián','miàn',''],trans:'Right in front of our hospital.'},
{speaker:'周明',text:'那你以后去医院就方便了。',py:'Nà nǐ yǐhòu qù yīyuàn jiù fāngbiàn le.',pyChars:['nà','nǐ','yǐ','hòu','qù','yī','yuàn','jiù','fāng','biàn','le',''],trans:'Then it will be convenient for you to go to the hospital.'}]},
{id:'18-2',lessonNo:18,textNo:2,lessonTitle:'我相信他们会同意的',lessonTitleEn:"I believe they'll agree",title:'在商店',titleEn:'In a Store',audio:'assets/18-2.mp3',sentences:[
{speaker:'小明',text:'妈妈，你看那只狗多可爱，眼睛大大的，嘴小小的，我们买回去吧。',py:'Māma, nǐ kàn nà zhī gǒu duō kě\'ài, yǎnjing dàdà de, zuǐ xiǎoxiǎo de, wǒmen mǎi huíqu ba.',pyChars:['mā','ma','','nǐ','kàn','nà','zhī','gǒu','duō','kě','ài','','yǎn','jing','dà','dà','de','','zuǐ','xiǎo','xiǎo','de','','wǒ','men','mǎi','huí','qu','ba',''],trans:"Mom, look how cute that dog is — big eyes, tiny mouth. Let's buy it and take it home."},
{speaker:'妈妈',text:'动物和小孩儿一样，都需要人照顾。买回家去，谁照顾它啊？',py:'Dòngwù hé xiǎoháir yíyàng, dōu xūyào rén zhàogù. Mǎi huí jiā qù, shéi zhàogù tā a?',pyChars:['dòng','wù','hé','xiǎo','hái','ér','yí','yàng','','dōu','xū','yào','rén','zhào','gù','','mǎi','huí','jiā','qù','','shéi','zhào','gù','tā','a',''],trans:"Animals, like children, need people to care for them. If we buy it, who'll take care of it?"},
{speaker:'小明',text:'我照顾啊。',py:'Wǒ zhàogù a.',pyChars:['wǒ','zhào','gù','a',''],trans:"I'll take care of it."},
{speaker:'妈妈',text:'这段时间你自己的衣服都没洗，你能照顾好它吗？',py:'Zhè duàn shíjiān nǐ zìjǐ de yīfu dōu méi xǐ, nǐ néng zhàogù hǎo tā ma?',pyChars:['zhè','duàn','shí','jiān','nǐ','zì','jǐ','de','yī','fu','dōu','méi','xǐ','','nǐ','néng','zhào','gù','hǎo','tā','ma',''],trans:"You haven't even washed your own clothes lately. Can you take good care of it?"},
{speaker:'小明',text:'只要你给我买，我就能照顾好它。',py:'Zhǐyào nǐ gěi wǒ mǎi, wǒ jiù néng zhàogù hǎo tā.',pyChars:['zhǐ','yào','nǐ','gěi','wǒ','mǎi','','wǒ','jiù','néng','zhào','gù','hǎo','tā',''],trans:"As long as you buy it for me, I can take good care of it."}]},
{id:'18-3',lessonNo:18,textNo:3,lessonTitle:'我相信他们会同意的',lessonTitleEn:"I believe they'll agree",title:'在公司',titleEn:'In the Company',audio:'assets/18-3.mp3',sentences:[
{speaker:'经理',text:'说说你为什么选择来我们公司工作。',py:'Shuōshuo nǐ wèi shénme xuǎnzé lái wǒmen gōngsī gōngzuò.',pyChars:['shuō','shuo','nǐ','wèi','shén','me','xuǎn','zé','lái','wǒ','men','gōng','sī','gōng','zuò',''],trans:'Tell me why you chose to work at our company.'},
{speaker:'学生',text:'贵公司不但很有名，而且工作环境好。',py:'Guì gōngsī búdàn hěn yǒumíng, érqiě gōngzuò huánjìng hǎo.',pyChars:['guì','gōng','sī','bú','dàn','hěn','yǒu','míng','','ér','qiě','gōng','zuò','huán','jìng','hǎo',''],trans:'Your company is not only famous but also has a good work environment.'},
{speaker:'经理',text:'做这个工作有点儿累，需要经常去外地。你家人同意吗？',py:'Zuò zhège gōngzuò yǒudiǎnr lèi, xūyào jīngcháng qù wàidì. Nǐ jiārén tóngyì ma?',pyChars:['zuò','zhè','ge','gōng','zuò','yǒu','diǎn','ér','lèi','','xū','yào','jīng','cháng','qù','wài','dì','','nǐ','jiā','rén','tóng','yì','ma',''],trans:"This job is a bit tiring; you'll need to travel often. Will your family agree?"},
{speaker:'学生',text:'只要我愿意，我相信他们就会同意的。',py:'Zhǐyào wǒ yuànyì, wǒ xiāngxìn tāmen jiù huì tóngyì de.',pyChars:['zhǐ','yào','wǒ','yuàn','yì','','wǒ','xiāng','xìn','tā','men','jiù','huì','tóng','yì','de',''],trans:'As long as I am willing, I believe they will agree.'},
{speaker:'经理',text:'好，那你明天来上班吧。关于这个工作，还有什么问题吗？',py:'Hǎo, nà nǐ míngtiān lái shàngbān ba. Guānyú zhège gōngzuò, hái yǒu shénme wèntí ma?',pyChars:['hǎo','','nà','nǐ','míng','tiān','lái','shàng','bān','ba','','guān','yú','zhè','ge','gōng','zuò','','hái','yǒu','shén','me','wèn','tí','ma',''],trans:'Good. Come to work tomorrow. Any other questions about this job?'},
{speaker:'学生',text:'没有了，谢谢您给我这个机会，我会努力的。',py:'Méiyǒu le, xièxie nín gěi wǒ zhège jīhuì, wǒ huì nǔlì de.',pyChars:['méi','yǒu','le','','xiè','xie','nín','gěi','wǒ','zhè','ge','jī','huì','','wǒ','huì','nǔ','lì','de',''],trans:"No more. Thank you for this opportunity. I'll work hard."}]},
{id:'18-4',lessonNo:18,textNo:4,lessonTitle:'我相信他们会同意的',lessonTitleEn:"I believe they'll agree",title:'短文',titleEn:'Short Passage',audio:'assets/18-4.mp3',sentences:[
{speaker:'旁白',text:'不同的国家有不同的文化，每种文化都有自己的特点。',py:'Bùtóng de guójiā yǒu bùtóng de wénhuà, měi zhǒng wénhuà dōu yǒu zìjǐ de tèdiǎn.',pyChars:['bù','tóng','de','guó','jiā','yǒu','bù','tóng','de','wén','huà','','měi','zhǒng','wén','huà','dōu','yǒu','zì','jǐ','de','tè','diǎn',''],trans:'Different countries have different cultures, and every culture has its own characteristics.'},
{speaker:'旁白',text:'到了一个新环境，你会觉得什么都很新鲜，',py:'Dàole yí ge xīn huánjìng, nǐ huì juéde shénme dōu hěn xīnxiān,',pyChars:['dào','le','yí','ge','xīn','huán','jìng','','nǐ','huì','jué','de','shén','me','dōu','hěn','xīn','xiān',''],trans:'When you arrive in a new environment, everything feels new,'},
{speaker:'旁白',text:'而且还会觉得有点奇怪：',py:'Érqiě hái huì juéde yǒudiǎn qíguài:',pyChars:['ér','qiě','hái','huì','jué','de','yǒu','diǎn','qí','guài',''],trans:'and you may also find some things a bit strange:'},
{speaker:'旁白',text:'有些国家的人名写在姓前面，',py:'Yǒuxiē guójiā de rénmíng xiě zài xìng qiánmiàn,',pyChars:['yǒu','xiē','guó','jiā','de','rén','míng','xiě','zài','xìng','qián','miàn',''],trans:'in some countries, given names come before family names,'},
{speaker:'旁白',text:'有些国家的人名写在姓后面，',py:'Yǒuxiē guójiā de rénmíng xiě zài xìng hòumiàn,',pyChars:['yǒu','xiē','guó','jiā','de','rén','míng','xiě','zài','xìng','hòu','miàn',''],trans:'in some countries, given names come after family names,'},
{speaker:'旁白',text:'但是只要经过一段时间，就会慢慢地习惯。',py:'Dànshì zhǐyào jīngguò yí duàn shíjiān, jiù huì mànman de xíguàn.',pyChars:['dàn','shì','zhǐ','yào','jīng','guò','yí','duàn','shí','jiān','','jiù','huì','màn','man','de','xí','guàn',''],trans:'but after some time, you will gradually get used to it.'}]},

/* ============ 第19课 ============ */
{id:'19-1',lessonNo:19,textNo:1,lessonTitle:'你没看出来吗',lessonTitleEn:"Didn't you recognize him",title:'在家',titleEn:'At Home',audio:'assets/19-1.mp3',sentences:[
{speaker:'爸爸',text:'女儿最近喜欢把头发放在耳朵后面，你知道为什么吗？',py:'Nǚ\'ér zuìjìn xǐhuan bǎ tóufa fàng zài ěrduo hòumiàn, nǐ zhīdào wèi shénme ma?',pyChars:['nǚ','ér','zuì','jìn','xǐ','huan','bǎ','tóu','fa','fàng','zài','ěr','duo','hòu','miàn','','nǐ','zhī','dào','wèi','shén','me','ma',''],trans:'Our daughter likes to put her hair behind her ears lately. Do you know why?'},
{speaker:'妈妈',text:'这样可以使她的脸看上去漂亮一些。',py:'Zhèyàng kěyǐ shǐ tā de liǎn kàn shàngqu piàoliang yìxiē.',pyChars:['zhè','yàng','kě','yǐ','shǐ','tā','de','liǎn','kàn','shàng','qu','piào','liang','yì','xiē',''],trans:'This makes her face look prettier.'},
{speaker:'爸爸',text:'我最近觉得她和以前不太一样了。',py:'Wǒ zuìjìn juéde tā hé yǐqián bú tài yíyàng le.',pyChars:['wǒ','zuì','jìn','jué','de','tā','hé','yǐ','qián','bú','tài','yí','yàng','le',''],trans:"I've been feeling she's different from before."},
{speaker:'妈妈',text:'女儿变化不小，她小时候喜欢短头发，像男孩子一样。',py:'Nǚ\'ér biànhuà bù xiǎo, tā xiǎo shíhou xǐhuan duǎn tóufa, xiàng nánháizi yíyàng.',pyChars:['nǚ','ér','biàn','huà','bù','xiǎo','','tā','xiǎo','shí','hòu','xǐ','huan','duǎn','tóu','fa','','xiàng','nán','hái','zi','yí','yàng',''],trans:'She has changed a lot. As a child, she liked short hair, just like a boy.'},
{speaker:'爸爸',text:'我也想起来了。她现在慢慢地开始像个女孩子了。',py:'Wǒ yě xiǎng qǐlai le. Tā xiànzài mànman de kāishǐ xiàng ge nǚháizi le.',pyChars:['wǒ','yě','xiǎng','qǐ','lai','le','','tā','xiàn','zài','màn','man','de','kāi','shǐ','xiàng','ge','nǚ','hái','zi','le',''],trans:'I remember now. She is slowly starting to be like a girl.'}]},
{id:'19-2',lessonNo:19,textNo:2,lessonTitle:'你没看出来吗',lessonTitleEn:"Didn't you recognize him",title:'在看照片',titleEn:'Looking at Photos',audio:'assets/19-2.mp3',sentences:[
{speaker:'小丽',text:'上次我们参加骑马比赛的照片，我选了几张洗出来了。',py:'Shàng cì wǒmen cānjiā qí mǎ bǐsài de zhàopiàn, wǒ xuǎn le jǐ zhāng xǐ chūlai le.',pyChars:['shàng','cì','wǒ','men','cān','jiā','qí','mǎ','bǐ','sài','de','zhào','piàn','','wǒ','xuǎn','le','jǐ','zhāng','xǐ','chū','lai','le',''],trans:"I selected and printed a few photos from our last horse-riding competition."},
{speaker:'同事',text:'快给我看看。骑得最快的这位是谁？',py:'Kuài gěi wǒ kànkan. Qí de zuì kuài de zhè wèi shì shéi?',pyChars:['kuài','gěi','wǒ','kàn','kan','','qí','de','zuì','kuài','de','zhè','wèi','shì','shéi',''],trans:'Show me. Who is this one that rode the fastest?'},
{speaker:'小丽',text:'你没看出来吗？他是小刚啊。',py:'Nǐ méi kàn chūlai ma? Tā shì Xiǎogāng a.',pyChars:['nǐ','méi','kàn','chū','lai','ma','','tā','shì','xiǎo','gāng','a',''],trans:"Haven't you recognized him? He's Xiaogang."},
{speaker:'同事',text:'怎么看上去跟现在不太一样？',py:'Zěnme kàn shàngqu gēn xiànzài bú tài yíyàng?',pyChars:['zěn','me','kàn','shàng','qu','gēn','xiàn','zài','bú','tài','yí','yàng',''],trans:"How come he looks a bit different from now?"},
{speaker:'小丽',text:'他上班穿西服、衬衫，比赛的时候穿的是运动服。',py:'Tā shàngbān chuān xīfú, chènshān, bǐsài de shíhou chuān de shì yùndòngfú.',pyChars:['tā','shàng','bān','chuān','xī','fú','','chèn','shān','','bǐ','sài','de','shí','hòu','chuān','de','shì','yùn','dòng','fú',''],trans:'He wears a suit and shirt to work, but sportswear for competitions.'},
{speaker:'同事',text:'他今天穿蓝西服，看上去像40多岁，还是穿运动服让他更年轻。',py:'Tā jīntiān chuān lán xīfú, kàn shàngqu xiàng sìshí duō suì, háishì chuān yùndòngfú ràng tā gèng niánqīng.',pyChars:['tā','jīn','tiān','chuān','lán','xī','fú','','kàn','shàng','qu','xiàng','sì','shí','duō','suì','','hái','shì','chuān','yùn','dòng','fú','ràng','tā','gèng','nián','qīng',''],trans:"He's wearing a blue suit today — he looks like he's in his forties. Sportswear makes him look younger."}]},
{id:'19-3',lessonNo:19,textNo:3,lessonTitle:'你没看出来吗',lessonTitleEn:"Didn't you recognize him",title:'在小丽家',titleEn:"At Xiaoli's Home",audio:'assets/19-3.mp3',sentences:[
{speaker:'朋友',text:'我们一年没见面了吧？',py:'Wǒmen yì nián méi jiànmiàn le ba?',pyChars:['wǒ','men','yì','nián','méi','jiàn','miàn','le','ba',''],trans:"It's been a year since we last met, right?"},
{speaker:'小丽',text:'听说你都有女儿了？她多大了？',py:'Tīngshuō nǐ dōu yǒu nǚ\'ér le? Tā duō dà le?',pyChars:['tīng','shuō','nǐ','dōu','yǒu','nǚ','ér','le','','tā','duō','dà','le',''],trans:'I heard you have a daughter now? How old is she?'},
{speaker:'朋友',text:'她去年秋天出生的，刚过完一岁生日。',py:'Tā qùnián qiūtiān chūshēng de, gāng guòwán yí suì shēngrì.',pyChars:['tā','qù','nián','qiū','tiān','chū','shēng','de','','gāng','guò','wán','yí','suì','shēng','rì',''],trans:'She was born last autumn, and just had her first birthday.'},
{speaker:'小丽',text:'她喜欢什么？我送给她。',py:'Tā xǐhuan shénme? Wǒ sòng gěi tā.',pyChars:['tā','xǐ','huan','shén','me','','wǒ','sòng','gěi','tā',''],trans:"What does she like? I'll give it to her."},
{speaker:'朋友',text:'她就喜欢听她爸爸学鸟叫。哭的时候，只要他爸爸学小鸟叫，她马上就安静下来了。',py:'Tā jiù xǐhuan tīng tā bàba xué niǎo jiào. Kū de shíhou, zhǐyào tā bàba xué xiǎo niǎo jiào, tā mǎshàng jiù ānjìng xiàlai le.',pyChars:['tā','jiù','xǐ','huan','tīng','tā','bà','ba','xué','niǎo','jiào','','kū','de','shí','hòu','','zhǐ','yào','tā','bà','ba','xué','xiǎo','niǎo','jiào','','tā','mǎ','shàng','jiù','ān','jìng','xià','lai','le',''],trans:"She just likes hearing her dad imitate bird calls. When she cries, as long as her dad imitates a little bird, she immediately quiets down."},
{speaker:'小丽',text:'啊？这个礼物我没办法送。',py:'A? Zhège lǐwù wǒ méi bànfǎ sòng.',pyChars:['a','','zhè','ge','lǐ','wù','wǒ','méi','bàn','fǎ','sòng',''],trans:"What? I can't give that as a gift."}]},
{id:'19-4',lessonNo:19,textNo:4,lessonTitle:'你没看出来吗',lessonTitleEn:"Didn't you recognize him",title:'短文',titleEn:'Short Passage',audio:'assets/19-4.mp3',sentences:[
{speaker:'旁白',text:'这次旅游，我去了不少地方，',py:'Zhè cì lǚyóu, wǒ qùle bù shǎo dìfang,',pyChars:['zhè','cì','lǚ','yóu','','wǒ','qù','le','bù','shǎo','dì','fang',''],trans:'On this trip, I visited many places,'},
{speaker:'旁白',text:'每个地方都让我非常难忘。',py:'Měi ge dìfang dōu ràng wǒ fēicháng nánwàng.',pyChars:['měi','ge','dì','fang','dōu','ràng','wǒ','fēi','cháng','nán','wàng',''],trans:'and every place was very memorable.'},
{speaker:'旁白',text:'我先去看了黄河，黄河是中国有名的大河，',py:'Wǒ xiān qù kànle Huáng Hé, Huáng Hé shì Zhōngguó yǒumíng de dà hé,',pyChars:['wǒ','xiān','qù','kàn','le','huáng','hé','','huáng','hé','shì','zhōng','guó','yǒu','míng','de','dà','hé',''],trans:'First I went to see the Yellow River, a famous big river in China,'},
{speaker:'旁白',text:'我坐在船上，一边看一边照相。',py:'Wǒ zuò zài chuán shàng, yìbiān kàn yìbiān zhàoxiàng.',pyChars:['wǒ','zuò','zài','chuán','shàng','','yì','biān','kàn','yì','biān','zhào','xiàng',''],trans:'I sat on a boat, looking and taking photos.'},
{speaker:'旁白',text:'一路上经过了很多地方，每个地方都不一样。',py:'Yí lù shàng jīngguòle hěn duō dìfang, měi ge dìfang dōu bù yíyàng.',pyChars:['yí','lù','shàng','jīng','guò','le','hěn','duō','dì','fang','','měi','ge','dì','fang','dōu','bù','yí','yàng',''],trans:'Along the way we passed many places, each different from the others.'},
{speaker:'旁白',text:'我想快点儿把照片发给大家，',py:'Wǒ xiǎng kuài diǎnr bǎ zhàopiàn fā gěi dàjiā,',pyChars:['wǒ','xiǎng','kuài','diǎn','ér','bǎ','zhào','piàn','fā','gěi','dà','jiā',''],trans:'I want to send the photos to everyone soon,'},
{speaker:'旁白',text:'叫朋友们也高兴高兴。',py:'Jiào péngyoumen yě gāoxìng gāoxìng.',pyChars:['jiào','péng','you','men','yě','gāo','xìng','gāo','xìng',''],trans:'so my friends can share the joy.'}]},

/* ============ 第20课 ============ */
{id:'20-1',lessonNo:20,textNo:1,lessonTitle:'我被他影响了',lessonTitleEn:"I've been influenced by him",title:'在休息室',titleEn:'In the Lounge',audio:'assets/20-1.mp3',sentences:[
{speaker:'小丽',text:'我的照相机被谁拿走了？怎么找不到了？',py:'Wǒ de zhàoxiàngjī bèi shéi ná zǒu le? Zěnme zhǎo bu dào le?',pyChars:['wǒ','de','zhào','xiàng','jī','bèi','shéi','ná','zǒu','le','','zěn','me','zhǎo','bu','dào','le',''],trans:'Who took my camera? How come I can\'t find it?'},
{speaker:'同事',text:'你再找找。是不是没带来？',py:'Nǐ zài zhǎozhao. Shì bu shì méi dàilai?',pyChars:['nǐ','zài','zhǎo','zhao','','shì','bu','shì','méi','dài','lai',''],trans:"Look again. Maybe you didn't bring it?"},
{speaker:'小丽',text:'我找了，没找到啊。',py:'Wǒ zhǎo le, méi zhǎodào a.',pyChars:['wǒ','zhǎo','le','','méi','zhǎo','dào','a',''],trans:"I looked, but couldn't find it."},
{speaker:'同事',text:'别难过，再买一个吧，公司东门外不就有一个大商场吗？',py:'Bié nánguò, zài mǎi yí ge ba, gōngsī dōngmén wài bú jiù yǒu yí ge dà shāngchǎng ma?',pyChars:['bié','nán','guò','','zài','mǎi','yí','ge','ba','','gōng','sī','dōng','mén','wài','bú','jiù','yǒu','yí','ge','dà','shāng','chǎng','ma',''],trans:"Don't be sad. Buy another one. Isn't there a big mall right outside the east gate of the company?"},
{speaker:'小丽',text:'但是我这个月信用卡里的钱已经花得差不多了。',py:'Dànshì wǒ zhège yuè xìnyòngkǎ li de qián yǐjīng huā de chàbuduō le.',pyChars:['dàn','shì','wǒ','zhè','ge','yuè','xìn','yòng','kǎ','li','de','qián','yǐ','jīng','huā','de','chà','bu','duō','le',''],trans:"But I've almost used up the money on my credit card this month."}]},
{id:'20-2',lessonNo:20,textNo:2,lessonTitle:'我被他影响了',lessonTitleEn:"I've been influenced by him",title:'在教室',titleEn:'In the Classroom',audio:'assets/20-2.mp3',sentences:[
{speaker:'小明',text:'你怎么突然关心起体育来了？',py:'Nǐ zěnme tūrán guānxīn qǐ tǐyù lai le?',pyChars:['nǐ','zěn','me','tū','rán','guān','xīn','qǐ','tǐ','yù','lai','le',''],trans:'Why have you suddenly become interested in sports?'},
{speaker:'朋友',text:'我的男朋友喜欢看足球比赛，我被他影响的。',py:'Wǒ de nánpéngyou xǐhuan kàn zúqiú bǐsài, wǒ bèi tā yǐngxiǎng de.',pyChars:['wǒ','de','nán','péng','you','xǐ','huan','kàn','zú','qiú','bǐ','sài','','wǒ','bèi','tā','yǐng','xiǎng','de',''],trans:'My boyfriend likes watching football matches. I was influenced by him.'},
{speaker:'小明',text:'看来只有爱，才能让人有变化。',py:'Kànlái zhǐyǒu ài, cái néng ràng rén yǒu biànhuà.',pyChars:['kàn','lái','zhǐ','yǒu','ài','','cái','néng','ràng','rén','yǒu','biàn','huà',''],trans:'It seems only love can make people change.'},
{speaker:'朋友',text:'是啊，为了和他的爱好一样，我天天看球赛。',py:'Shì a, wèile hé tā de àihào yíyàng, wǒ tiāntiān kàn qiúsài.',pyChars:['shì','a','','wèi','le','hé','tā','de','ài','hào','yí','yàng','','wǒ','tiān','tiān','kàn','qiú','sài',''],trans:"Yes. To share his hobby, I watch matches every day."},
{speaker:'小明',text:'除了足球，他还影响你什么了？',py:'Chúle zúqiú, tā hái yǐngxiǎng nǐ shénme le?',pyChars:['chú','le','zú','qiú','','tā','hái','yǐng','xiǎng','nǐ','shén','me','le',''],trans:'Besides football, what else has he influenced you in?'},
{speaker:'朋友',text:'我最近天天上网玩儿游戏，我的成绩差极了。',py:'Wǒ zuìjìn tiāntiān shàngwǎng wánr yóuxì, wǒ de chéngjì chà jí le.',pyChars:['wǒ','zuì','jìn','tiān','tiān','shàng','wǎng','wán','ér','yóu','xì','','wǒ','de','chéng','jì','chà','jí','le',''],trans:"Lately I've been playing games online every day, and my grades are terrible."}]},
{id:'20-3',lessonNo:20,textNo:3,lessonTitle:'我被他影响了',lessonTitleEn:"I've been influenced by him",title:'在饭馆',titleEn:'In the Restaurant',audio:'assets/20-3.mp3',sentences:[
{speaker:'朋友',text:'那个拿着碗吃饭的人是你哥哥吗？他和你长得真像。',py:'Nàge názhe wǎn chīfàn de rén shì nǐ gēge ma? Tā hé nǐ zhǎng de zhēn xiàng.',pyChars:['nà','ge','ná','zhe','wǎn','chī','fàn','de','rén','shì','nǐ','gē','ge','ma','','tā','hé','nǐ','zhǎng','de','zhēn','xiàng',''],trans:'Is that person eating with a bowl your older brother? He looks just like you.'},
{speaker:'大卫',text:'我们经常被别人认错。',py:'Wǒmen jīngcháng bèi biérén rèncuò.',pyChars:['wǒ','men','jīng','cháng','bèi','bié','rén','rèn','cuò',''],trans:'We are often mistaken for each other.'},
{speaker:'朋友',text:'只有你们的爸爸妈妈才能分出来哪个是哥哥，哪个是弟弟吧。',py:'Zhǐyǒu nǐmen de bàba māma cái néng fēn chūlai nǎge shì gēge, nǎge shì dìdi ba.',pyChars:['zhǐ','yǒu','nǐ','men','de','bà','ba','mā','ma','cái','néng','fēn','chū','lai','nǎ','ge','shì','gē','ge','','nǎ','ge','shì','dì','di','ba',''],trans:'Only your parents can tell which is the older brother and which is the younger one.'},
{speaker:'大卫',text:'除了父母以外，还有我们自己也能啊。',py:'Chúle fùmǔ yǐwài, hái yǒu wǒmen zìjǐ yě néng a.',pyChars:['chú','le','fù','mǔ','yǐ','wài','','hái','yǒu','wǒ','men','zì','jǐ','yě','néng','a',''],trans:'Besides our parents, we can tell too.'},
{speaker:'朋友',text:'你们两个除了长得像，还有什么相同的地方？',py:'Nǐmen liǎng ge chúle zhǎng de xiàng, hái yǒu shénme xiāngtóng de dìfang?',pyChars:['nǐ','men','liǎng','ge','chú','le','zhǎng','de','xiàng','','hái','yǒu','shén','me','xiāng','tóng','de','dì','fang',''],trans:'Besides looking alike, what else do you two have in common?'},
{speaker:'大卫',text:'我们住在同一个楼、同一个房间……',py:'Wǒmen zhù zài tóng yí ge lóu, tóng yí ge fángjiān……',pyChars:['wǒ','men','zhù','zài','tóng','yí','ge','lóu','','tóng','yí','ge','fáng','jiān',''],trans:'We live in the same building, the same room...'}]},
{id:'20-4',lessonNo:20,textNo:4,lessonTitle:'我被他影响了',lessonTitleEn:"I've been influenced by him",title:'短文',titleEn:'Short Passage',audio:'assets/20-4.mp3',sentences:[
{speaker:'旁白',text:'年轻人遇到难题，常常很着急，不知道怎么办。',py:'Niánqīng rén yùdào nántí, chángcháng hěn zháojí, bù zhīdào zěnme bàn.',pyChars:['nián','qīng','rén','yù','dào','nán','tí','','cháng','cháng','hěn','zháo','jí','','bù','zhī','dào','zěn','me','bàn',''],trans:"When young people face a difficult problem, they often get anxious and don't know what to do."},
{speaker:'旁白',text:'其实，不同的问题有不同的解决办法。',py:'Qíshí, bùtóng de wèntí yǒu bùtóng de jiějué bànfǎ.',pyChars:['qí','shí','','bù','tóng','de','wèn','tí','yǒu','bù','tóng','de','jiě','jué','bàn','fǎ',''],trans:'Actually, different problems have different solutions.'},
{speaker:'旁白',text:'有些问题看上去很难，',py:'Yǒuxiē wèntí kàn shàngqu hěn nán,',pyChars:['yǒu','xiē','wèn','tí','kàn','shàng','qu','hěn','nán',''],trans:'Some problems look very difficult,'},
{speaker:'旁白',text:'但是做起来非常简单，',py:'Dànshì zuò qǐlai fēicháng jiǎndān,',pyChars:['dàn','shì','zuò','qǐ','lai','fēi','cháng','jiǎn','dān',''],trans:'but are very simple in practice,'},
{speaker:'旁白',text:'所以得试着做做。',py:'Suǒyǐ děi shìzhe zuòzuo.',pyChars:['suǒ','yǐ','děi','shì','zhe','zuò','zuo',''],trans:'so you have to give them a try.'},
{speaker:'旁白',text:'有些问题看上去虽然简单，但是解决起来难极了。',py:'Yǒuxiē wèntí kàn shàngqu suīrán jiǎndān, dànshì jiějué qǐlai nán jí le.',pyChars:['yǒu','xiē','wèn','tí','kàn','shàng','qu','suī','rán','jiǎn','dān','','dàn','shì','jiě','jué','qǐ','lai','nán','jí','le',''],trans:'Some problems look simple but are extremely hard to solve.'},
{speaker:'旁白',text:'所以只有真正做事情的时候，才能了解有多难。',py:'Suǒyǐ zhǐyǒu zhēnzhèng zuò shìqing de shíhou, cái néng liǎojiě yǒu duō nán.',pyChars:['suǒ','yǐ','zhǐ','yǒu','zhēn','zhèng','zuò','shì','qing','de','shí','hòu','','cái','néng','liǎo','jiě','yǒu','duō','nán',''],trans:'So only when you actually do something can you understand how difficult it is.'},
{speaker:'旁白',text:'不过，我们一定要相信：多么难的问题，都会被解决的。',py:'Búguò, wǒmen yídìng yào xiāngxìn: duōme nán de wèntí, dōu huì bèi jiějué de.',pyChars:['bú','guò','','wǒ','men','yí','dìng','yào','xiāng','xìn','','duō','me','nán','de','wèn','tí','','dōu','huì','bèi','jiě','jué','de',''],trans:"However, we must believe: no matter how difficult a problem is, it will be solved."}]}
);